let fighter = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w3jw-de938798-b424-41a6-97a3-2da7cf54d589.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2FiYTFhNzU2LWQ5NTUtNDNmNi1hMmU5LTViN2Q2MDQwNjg1NFwvZDUwdzNqdy1kZTkzODc5OC1iNDI0LTQxYTYtOTdhMy0yZGE3Y2Y1NGQ1ODkucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.HGh80g4xxzz2u9_PBJAONxCOaoxy1OW9J2yi0oKhHuA'
let lightning = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w476-824f2616-a647-4a21-a284-8a35db3dd34b.png/v1/fit/w_720,h_720/electric_energy_by_humac1_d50w476-375w-2x.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NzIwIiwicGF0aCI6IlwvZlwvYWJhMWE3NTYtZDk1NS00M2Y2LWEyZTktNWI3ZDYwNDA2ODU0XC9kNTB3NDc2LTgyNGYyNjE2LWE2NDctNGEyMS1hMjg0LThhMzVkYjNkZDM0Yi5wbmciLCJ3aWR0aCI6Ijw9NzIwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.TWz0rw0cPCDqnXtwripN9OXA1V9qf5jNwrZYea4YZ7w'
let water = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w3fi-85063943-452c-4b80-8db1-5cf8ff52df52.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2FiYTFhNzU2LWQ5NTUtNDNmNi1hMmU5LTViN2Q2MDQwNjg1NFwvZDUwdzNmaS04NTA2Mzk0My00NTJjLTRiODAtOGRiMS01Y2Y4ZmY1MmRmNTIucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.voroYLPZMwgOCJjmkVuK6GepgSaDWAjj25Ptq5CuGJg'
let pyschic = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w3p6-aa8c3894-d7bf-450b-99be-f608d14e1e4a.png/v1/fit/w_720,h_720/psychic_energy_by_humac1_d50w3p6-375w-2x.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NzIwIiwicGF0aCI6IlwvZlwvYWJhMWE3NTYtZDk1NS00M2Y2LWEyZTktNWI3ZDYwNDA2ODU0XC9kNTB3M3A2LWFhOGMzODk0LWQ3YmYtNDUwYi05OWJlLWY2MDhkMTRlMWU0YS5wbmciLCJ3aWR0aCI6Ijw9NzIwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.X66lXufkAxkVXIW4UYQjAbHyGeoKZ9pBYVr-q8__wHo'
let dark = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w4az-9be9ea46-fdf8-4e18-957e-9c7fcded42e5.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2FiYTFhNzU2LWQ5NTUtNDNmNi1hMmU5LTViN2Q2MDQwNjg1NFwvZDUwdzRhei05YmU5ZWE0Ni1mZGY4LTRlMTgtOTU3ZS05YzdmY2RlZDQyZTUucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.BrPQc3irmKVsAQ5EGkKyiVD1uJWriOOxsupE6eGEzbo'
let wind = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/b0b4c759-ad9c-4425-a9f4-ab89e2fd9837/dfqnx68-7fe93ac3-842b-4884-8e62-b8f60a4611f1.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2IwYjRjNzU5LWFkOWMtNDQyNS1hOWY0LWFiODllMmZkOTgzN1wvZGZxbng2OC03ZmU5M2FjMy04NDJiLTQ4ODQtOGU2Mi1iOGY2MGE0NjExZjEucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.YhuFxSx0nTcNbc7JJB74NP8mzfASk6vSJHIEXLWEfAg'
let earth = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/472f4a44-0b68-46a9-bfd1-ffca5f5d411f/dhcbrn5-e71b4cf7-1a9a-4179-95dc-52386fe03cd5.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzQ3MmY0YTQ0LTBiNjgtNDZhOS1iZmQxLWZmY2E1ZjVkNDExZlwvZGhjYnJuNS1lNzFiNGNmNy0xYTlhLTQxNzktOTVkYy01MjM4NmZlMDNjZDUucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.xoGUxe8T8CLCmOdKrMnEyNpg3bwi8YmFZNQ9nh5WVRs'
let grass = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w40k-75281ddb-5dc8-4eb8-9321-d5c901815eed.png/v1/fit/w_720,h_720/leaf_energy_by_humac1_d50w40k-375w-2x.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NzIwIiwicGF0aCI6IlwvZlwvYWJhMWE3NTYtZDk1NS00M2Y2LWEyZTktNWI3ZDYwNDA2ODU0XC9kNTB3NDBrLTc1MjgxZGRiLTVkYzgtNGViOC05MzIxLWQ1YzkwMTgxNWVlZC5wbmciLCJ3aWR0aCI6Ijw9NzIwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.hkzFeGcwL8-ZytHLvV07CmX3RHjcImRYgtZkUHGuNzM'
let wood = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/0726fbdd-a6a6-4871-bed6-e8e0b9ce2af0/d60ip66-33ba9598-ad1f-44c0-bf01-97bc7087537c.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzA3MjZmYmRkLWE2YTYtNDg3MS1iZWQ2LWU4ZTBiOWNlMmFmMFwvZDYwaXA2Ni0zM2JhOTU5OC1hZDFmLTQ0YzAtYmYwMS05N2JjNzA4NzUzN2MucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.1PERUsrBVM1PMauDQqU0n6-1d5x27xua3Zy85kfVrBg'
let fire = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w437-315a34c4-85c2-4d07-ae4d-6b42a25233bf.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2FiYTFhNzU2LWQ5NTUtNDNmNi1hMmU5LTViN2Q2MDQwNjg1NFwvZDUwdzQzNy0zMTVhMzRjNC04NWMyLTRkMDctYWU0ZC02YjQyYTI1MjMzYmYucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.kytndezX-kNW72WN893L_sOKoTnQYmvnqvJ79VVV8w8'
let fairy = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/0726fbdd-a6a6-4871-bed6-e8e0b9ce2af0/d6jtiuy-f4dc7bea-beb7-417b-ba85-736ae9f5c030.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzA3MjZmYmRkLWE2YTYtNDg3MS1iZWQ2LWU4ZTBiOWNlMmFmMFwvZDZqdGl1eS1mNGRjN2JlYS1iZWI3LTQxN2ItYmE4NS03MzZhZTlmNWMwMzAucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.A7u24I0bww1aTVrw5_r3CLN3r22RCZ0UwN64WCHUBMo'
let ghost = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/0726fbdd-a6a6-4871-bed6-e8e0b9ce2af0/d60owgy-a7268d0a-16b8-4fcd-ba33-8693f0bd401e.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzA3MjZmYmRkLWE2YTYtNDg3MS1iZWQ2LWU4ZTBiOWNlMmFmMFwvZDYwb3dneS1hNzI2OGQwYS0xNmI4LTRmY2QtYmEzMy04NjkzZjBiZDQwMWUucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.YviN7Ut0mDSC85LB34cdO43vBTexZICfV-w_C-iUVgk'
let sage = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w4gu-bcf44127-7bc3-468d-b148-1af8cf4e7ac0.png/v1/fit/w_720,h_720/colorless_energy_by_humac1_d50w4gu-375w-2x.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NzIwIiwicGF0aCI6IlwvZlwvYWJhMWE3NTYtZDk1NS00M2Y2LWEyZTktNWI3ZDYwNDA2ODU0XC9kNTB3NGd1LWJjZjQ0MTI3LTdiYzMtNDY4ZC1iMTQ4LTFhZjhjZjRlN2FjMC5wbmciLCJ3aWR0aCI6Ijw9NzIwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.I2hRnHXhqZrAh05uX4UyxVC8C-iVQrj00LWU7nvS9C8'
const database = [
    {
        name: 'Toji',
        nen_type: 'Enhancer',
        element: 'Ghost',
        elm: ghost,
        hp: 3500,
        //PHYSICAL
        attack: 220,
        defense: 200,
        critical: .40,
        strength: 1.6,
        //MAGIC
        elm_attack: 121,
        elm_defense: 153,
        elm_efficiency: 1.5,
        potency: .15,
        //WEAPON
        weapon: 300,
        shield: 238,
        curse_crit: 0.0,
        weaponCurse: 'Katana',
        weapon_amount: 0,
        //SPEED / LUCK
        accuracy: 7,
        evasion: 9,
        luck: 3,
        stun: .06,
        //GENJUTSU
        genjutsu: 1,
        gen_power: 0,
        willpower: 3,
        chakra: 0,
        chakra_rec: 3,
        drain: 0,
        //CURSE
        cursed_energy: 5,
        cursed_recovery: 100,
        negative_energy: 0,
        cursed_tech: 'Inventory-Curse - Change Weapons',
        curse_amount: 0,
        curse_duration: 1,
        curse_cost: 1,
        //DOMAIN
        dom_purity: 5,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Increase Defense by 15%',
        ninJutsu2cost: 12,
        ninJutsu2Dmg: 180,
        nin2amount: .15,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Increase Magic Defense by 20%",
        nin_cost: 15,
        ninjutsu_pow: 215,
        ninamount: .20,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Domain Purity by 4',
        buff2: 'Reduce Critical by 70%',
        buff_acc: 60,
        buff2_acc: 50,
        image: 'https://i0.wp.com/ovicio.com.br/wp-content/uploads/2023/06/20230626-fzgi5egxsainwyd.jpg?resize=555%2C555&ssl=1'
    },
    {
        name: 'Nanami',
        nen_type: 'Enhancer',
        element: 'Fighter',
        elm: fighter,
        hp: 3289,
        //PHYSICAL
        attack: 232,
        defense: 200,
        critical: .18,
        strength: 1.5,
        //MAGIC
        elm_attack: 127,
        elm_defense: 186,
        elm_efficiency: 1,
        potency: 1,
        //WEAPON
        weapon: 274,
        shield: 236,
        curse_crit: .50,
        weaponCurse: 'Shield',
        weapon_amount: 10,
        //SPEED / LUCK
        accuracy: 7,
        evasion: 3,
        luck: 6,
        stun: .08,
        //GENJUTSU
        genjutsu: 3,
        gen_power: 25,
        willpower: 8,
        chakra: 0,
        chakra_rec: 4,
        drain: 4,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 0,
        negative_energy: 20,
        cursed_tech: 'Overtime - Increase Curse Tool by 60',
        curse_amount: 60,
        curse_duration: 100,
        curse_cost: 30,
        //DOMAIN
        dom_purity: 2,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Collapse - Decrease Evasion by 1',
        ninJutsu2cost: 14,
        ninJutsu2Dmg: 180,
        nin2amount: 1,
        ninEnhance: false,
        //ULTIMATE
        ninjutsu: "Ratio-Technique - Increase Wither by 10",
        nin_cost: 16,
        ninjutsu_pow: 240,
        ninamount: 10,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Curse Recovery by 10',
        buff2: 'Decrease Critical by 20%',
        buff_acc: 50,
        buff2_acc: 50,
        image: 'https://64.media.tumblr.com/bee5b4150e08d22f7351d037813cd8b9/13fcef64824dd1b2-da/s1280x1920/f260dbaffb68a41c3554c15561f909841cf1b9dc.jpg'
    },
    {
        name: 'Noritoshi',
        nen_type: 'Emitter',
        element: 'Fire',
        elm: ghost,
        hp: 2957,
        //PHYSICAL
        attack: 135,
        defense: 128,
        critical: .12,
        strength: .10,
        //MAGIC
        elm_attack: 115,
        elm_defense: 191,
        elm_efficiency: 1.15,
        potency: .25,
        //WEAPON
        weapon: 256,
        shield: 139,
        curse_crit: .70,
        weaponCurse: 'Critical',
        weapon_amount: .08,
        //SPEED / LUCK
        accuracy: 9,
        evasion: 5,
        luck: 7,
        stun: .06,
        //GENJUTSU
        genjutsu: 8,
        gen_power: 25,
        willpower: 7,
        chakra: 0,
        chakra_rec: 4,
        drain: 7,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 50,
        negative_energy: 16,
        cursed_tech: 'Convergence - Deal 315 damage',
        curse_amount: 315,
        curse_duration: 1,
        curse_cost: 16,
        //DOMAIN
        dom_purity: 3,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Flowing-Red-Scale - Increase Potency by 35%',
        ninJutsu2cost: 13,
        ninJutsu2Dmg: 155,
        nin2amount: .35,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: 'Crimson-Binding - Trap opponent for 2 turns',
        nin_cost: 26,
        ninjutsu_pow: 135,
        ninamount: 0,
        ultEnhance: false,
        //BUFFS
        buff: 'Double Magic Attack',
        buff2: 'Halve Potency',
        buff_acc: 55,
        buff2_acc: 45,
        image: 'https://64.media.tumblr.com/11d79e538d170ebc91403fa7825be14a/ac5ce7753d2dffd1-7d/s1280x1920/5e3752a4fc826febaef45197801b139f48d244de.jpg'
    },
    {
        name: 'Nobunaga',
        nen_type: 'Transmuter',
        element: 'Dark',
        elm: wood,
        hp: 3152,
        //PHYSICAL
        attack: 185,
        defense: 140,
        critical: .35,
        strength: 2,
        //MAGIC
        elm_attack: 157,
        elm_defense: 232,
        elm_efficiency: .12,
        potency: .16,
        //WEAPON
        weapon: 270,
        shield: 164,
        curse_crit: .17,
        weaponCurse: 'Purity',
        weapon_amount: 1,
        //SPEED / LUCK
        accuracy: 9,
        evasion: 5,
        luck: 3,
        stun: .08,
        //GENJUTSU
        genjutsu: 5,
        gen_power: 10,
        willpower: 7,
        chakra: 0,
        chakra_rec: 3,
        drain: 2,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 49,
        negative_energy: 18,
        cursed_tech: 'Blade of the Right Hand - 90% Critical rate',
        curse_amount: .55,
        curse_duration: 8,
        curse_cost: 21,
        //DOMAIN
        dom_purity: 3,
        dom_lethal: 85,
        dom_duration: 6,
        dom_cost: 34,
        //NINJUTSU
        ninjutsu2: 'En-Strike - Decrease Attack by 5%',
        ninJutsu2cost: 15,
        ninJutsu2Dmg: 165,
        nin2amount: .05,
        ninEnhance: false,
        //ULTIMATE
        ninjutsu: "Iaidō-Master - Decrease Magic by 5%",
        nin_cost: 15,
        ninjutsu_pow: 165,
        ninamount: .05,
        ultEnhance: false,
        //BUFFS
        buff: 'Double Domain Purity',
        buff2: 'Decrease Will Power by 20%',
        buff_acc: 60,
        buff2_acc: 60,
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/4/46/HxH2011_EP50_Nobunaga_Portrait.png/revision/latest?cb=20230122183803'
    },
    {
        name: 'Mikasa',
        nen_type: 'Enhancer',
        element: 'Lightning',
        elm: earth,
        hp: 2971,
        //PHYSICAL
        attack: 228,
        defense: 173,
        critical: .38,
        strength: 1.4,
        //MAGIC
        elm_attack: 241,
        elm_defense: 126,
        elm_efficiency: 1.2,
        potency: .20,
        //WEAPON
        weapon: 245,
        shield: 169,
        curse_crit: .20,
        weaponCurse: 'Defense',
        weapon_amount: 25,
        //SPEED / LUCK
        accuracy: 7,
        evasion: 8,
        luck: 6,
        stun: .05,
        //GENJUTSU
        genjutsu: 5,
        gen_power: 15,
        willpower: 2,
        chakra: 0,
        chakra_rec: 2,
        drain: 4,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 27,
        negative_energy: 14,
        cursed_tech: 'Projection-Sorcery - Increase Evasion by 8',
        curse_amount: 8,
        curse_duration: 8,
        curse_cost: 17,
        //DOMAIN
        dom_purity: 5,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Thunder-Spear - Increase Effieciency by 35%',
        ninJutsu2cost: 13,
        ninJutsu2Dmg: 245,
        nin2amount: .35,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Awakening - Increase Critical by 80%",
        nin_cost: 26,
        ninjutsu_pow: 0,
        ninamount: .80,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Shield by 25%',
        buff2: 'Decrease Accuracy by 2',
        buff_acc: 70,
        buff2_acc: 70,
        image: 'https://preview.redd.it/what-do-you-dislike-about-mikasas-character-v0-s42udm18c6bb1.jpg?auto=webp&s=e7c072a57d924d5aa9bd83dbae93ed7bc93c160f'
    },
    {
        name: 'Might Guy',
        nen_type: 'Enhancer',
        element: 'Fire',
        elm: fire,
        hp: 3115,
        //PHYSICAL
        attack: 242,
        defense: 185,
        critical: .20,
        strength: 1.8,
        //MAGIC
        elm_attack: 152,
        elm_defense: 174,
        elm_efficiency: 1.4,
        potency: .15,
        //WEAPON
        weapon: 280,
        shield: 180,
        curse_crit: .23,
        weaponCurse: 'Curse',
        weapon_amount: 8,
        //SPEED / LUCK
        accuracy: 5,
        evasion: 6,
        luck: 2,
        stun: .03,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 15,
        willpower: 5,
        chakra: 0,
        chakra_rec: 5,
        drain: 3,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 30,
        negative_energy: 15,
        cursed_tech: '8th-Gate of death - Double Attack',
        curse_amount: 242,
        curse_duration: 100,
        curse_cost: 36,
        //DOMAIN
        dom_purity: 7,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Morning Peacock',
        ninJutsu2cost: 28,
        ninJutsu2Dmg: 350,
        nin2amount: 0,
        ninEnhance: false,
        //ULTIMATE
        ninjutsu: "Daytime-Tiger",
        nin_cost: 38,
        ninjutsu_pow: 500,
        ninamount: 0,
        ultEnhance: false,
        //BUFFS
        buff: 'Increase Curse Recovery by 15',
        buff2: 'Halve Genjutsu',
        buff_acc: 50,
        buff2_acc: 50,
        image: 'https://i.pinimg.com/736x/25/80/3b/25803b13e5a6e1b7420070889dc5ecc6.jpg'
    },
    {
        name: 'Hanzo',
        nen_type: 'Enhancer',
        element: 'Fighter',
        elm: fighter,
        hp: 3000,
        //PHYSICAL
        attack: 198,
        defense: 177,
        critical: 0.22,
        strength: 1.4,
        //MAGIC
        elm_attack: 126,
        elm_defense: 136,
        elm_efficiency: 1.2,
        potency: .13,
        //WEAPON
        weapon: 252,
        shield: 189,
        curse_crit: 0.10,
        weaponCurse: 'Accuracy',
        weapon_amount: 1,
        //SPEED / LUCK
        accuracy: 8,
        evasion: 7,
        luck: 5,
        stun: .04,
        //GENJUTSU
        genjutsu: 9,
        gen_power: 65,
        willpower: 8,
        chakra: 0,
        chakra_rec: 6,
        drain: 3,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 17,
        negative_energy: 23,
        cursed_tech: 'Reverse-Flow-Recovery - Double Chakra Recovery',
        curse_amount: 6,
        curse_duration: 6,
        curse_cost: 12,
        //DOMAIN
        dom_purity: 2,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Hidden-Blades - Increase Attack by 10%',
        ninJutsu2cost: 14,
        ninJutsu2Dmg: 125,
        nin2amount: .10,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: 'Art-of-the-Doppelganger - Decrease Willpower by 2',
        nin_cost: 21,
        ninjutsu_pow: 155,
        ninamount: 2,
        ultEnhance: false,
        //BUFFS
        buff: 'Increase Defense by 35%',
        buff2: 'Decrease Critical by 15%',
        buff_acc: 55,
        buff2_acc: 15,
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/a/aa/HxH2011_EP3_Hanzo_Portrait.png/revision/latest?cb=20221007164354'
    },
    {
        name: 'Kasumi',
        nen_type: 'Transmuter',
        element: 'Water',
        elm: water,
        hp: 2872,
        //PHYSICAL
        attack: 188,
        defense: 161,
        critical: .45,
        strength: 1.4,
        //MAGIC
        elm_attack: 156,
        elm_defense: 248,
        elm_efficiency: 1.2,
        potency: .10,
        //WEAPON
        weapon: 242,
        shield: 133,
        curse_crit: .20,
        weaponCurse: 'Magic',
        weapon_amount: 23,
        //SPEED / LUCK
        accuracy: 7,
        evasion: 5,
        luck: 8,
        stun: .12,
        //GENJUTSU
        genjutsu: 4,
        gen_power: 50,
        willpower: 2,
        chakra: 0,
        chakra_rec: 7,
        drain: 6,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 32,
        negative_energy: 20,
        cursed_tech: 'Simple-Domain - Increase Defense by 100',
        curse_amount: 100,
        curse_duration: 6,
        curse_cost: 20,
        //DOMAIN
        dom_purity: 1,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Batto-Sword-Drawing Increase Stun by 10%',
        ninJutsu2cost: 13,
        ninJutsu2Dmg: 170,
        nin2amount: .10,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "New-Shadow-Style",
        nin_cost: 24,
        ninjutsu_pow: 330,
        ninamount: 0,
        ultEnhance: false,
        //BUFFS
        buff: 'Double Genjutsu',
        buff2: 'Decrease Potency by 40%',
        buff_acc: 50,
        buff2_acc: 50,
        image: 'https://i.pinimg.com/736x/7d/f8/b8/7df8b897b7ac8b7233c8ce4882de5fbd.jpg'
    },
    {
        name: 'Katana Man',
        nen_type: 'Transmuter',
        element: 'Fighter',
        elm: fighter,
        hp: 3395,
        //PHYSICAL
        attack: 185,
        defense: 266,
        critical: .20,
        strength: 1.6,
        //MAGIC
        elm_attack: 133,
        elm_defense: 180,
        elm_efficiency: 1.2,
        potency: 0.12,
        //WEAPON
        weapon: 258,
        shield: 242,
        curse_crit: 0.24,
        weaponCurse: 'Attack',
        weapon_amount: 10,
        //SPEED / LUCK
        accuracy: 4,
        evasion: 5,
        luck: 5,
        stun: .02,
        //GENJUTSU
        genjutsu: 1,
        gen_power: 0,
        willpower: 2,
        chakra: 0,
        chakra_rec: 4,
        drain: 5,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 49,
        negative_energy: 34,
        cursed_tech: 'Dismantle - Deal 325 Damage',
        curse_amount: 325,
        curse_duration: 1,
        curse_cost: 20,
        //DOMAIN
        dom_purity: 3,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Sword-Draw-Dash - Decrease Evasion by 1',
        ninJutsu2cost: 18,
        ninJutsu2Dmg: 140,
        nin2amount: 1,
        ninEnhance: false,
        //ULTIMATE
        ninjutsu: 'Blood-Consumption - Recover 365 HP',
        nin_cost: 27,
        ninjutsu_pow: 0,
        ninamount: 365,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Evasion by 3',
        buff2: 'Decrease Defense by 40%',
        buff_acc: 40,
        buff2_acc: 30,
        image: 'https://i.pinimg.com/736x/b8/d4/38/b8d438d6a6db0c7b2f6080558e3d993f.jpg'
    },
    {
        name: 'Maki',
        nen_type: 'Transmuter',
        element: 'Wind',
        elm: wind,
        hp: 2863,
        //PHYSICAL
        attack: 204,
        defense: 170,
        critical: .45,
        strength: 1.3,
        //MAGIC
        elm_attack: 146,
        elm_defense: 190,
        elm_efficiency: 1.3,
        potency: .18,
        //WEAPON
        weapon: 247,
        shield: 224,
        curse_crit: .14,
        weaponCurse: 'Recovery',
        weapon_amount: 1,
        //SPEED / LUCK
        accuracy: 7,
        evasion: 8,
        luck: 4,
        stun: .09,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 10,
        willpower: 3,
        chakra: 0,
        chakra_rec: 5,
        drain: 4,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 10,
        negative_energy: 10,
        cursed_tech: "Falling-Blossom-Emotion",
        curse_amount: 8,
        curse_duration: 6,
        curse_cost: 12,
        //DOMAIN
        dom_purity: 2,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Playful-Cloud - Increase Attack by 6%',
        ninJutsu2cost: 12,
        ninJutsu2Dmg: 160,
        nin2amount: .06,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Heavenly-Restriction - Increase Defense by 40%",
        nin_cost: 20,
        ninjutsu_pow: 180,
        ninamount: .40,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Chakra Recovery by 2',
        buff2: 'Decrease Attack by 25%',
        buff_acc: 70,
        buff2_acc: 60,
        image: 'https://thicc.mywaifulist.moe/waifus/26112/2ce0a9ba09c15a29b46fbda0ba73c91ce081e3e31b9d5e4186791980fa31fe4c_thumb.png'
    },
    {
        name: 'Chainsaw Man',
        nen_type: 'Conjuror',
        element: 'Lightning',
        elm: lightning,
        hp: 3053,
        //PHYSICAL
        attack: 196,
        defense: 229,
        critical: .23,
        strength: 1.75,
        //MAGIC
        elm_attack: 120,
        elm_defense: 166,
        elm_efficiency: 2.0,
        potency: .30,
        //WEAPON
        weapon: 284,
        shield: 201,
        curse_crit: .28,
        weaponCurse: 'Weapon',
        weapon_amount: 12,
        //SPEED / LUCK
        accuracy: 4,
        evasion: 5,
        luck: 9,
        drain: 3,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 40,
        willpower: 2,
        chakra: 0,
        chakra_rec: 4,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 50,
        cursed_tech: 'Devil-Transformation - Increase Weapon by 100',
        negative_energy: 25,
        curse_amount: 100,
        curse_duration: 6,
        curse_cost: 20,
        //DOMAIN
        dom_purity: 3,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Chain-Entanglement - Decrease Evasion by 1',
        ninJutsu2cost: 16,
        ninJutsu2Dmg: 190,
        nin2amount: 1,
        ninEnhance: false,
        //ULTIMATE
        ninjutsu: "Blood-Consumption - Recover 300 HP",
        nin_cost: 26,
        ninjutsu_pow: 0,
        ninamount: 300,
        ultEnhance: true,
        //BUFFS
        buff: 'Triple Domain Purity',
        buff2: 'Decrease Luck by 2',
        buff_acc: 50,
        buff2_acc: 65,
        image: 'https://i.pinimg.com/736x/c4/87/23/c48723566f7392d5218218a17171294b.jpg'
    },
    {
        name: 'Hunter Killua',
        nen_type: 'Transmuter',
        element: 'Lightning',
        elm: lightning,
        hp: 2822,
        //PHYSICAL
        attack: 184,
        defense: 188,
        critical: .32,
        strength: 1.4,
        //MAGIC
        elm_attack: 127,
        elm_defense: 134,
        elm_efficiency: 1.3,
        potency: .10,
        //WEAPON
        weapon: 241,
        shield: 136,
        curse_crit: .22,
        weaponCurse: 'Gen-Power',
        weapon_amount: 10,
        //SPEED / LUCK
        accuracy: 8,
        evasion: 5,
        luck: 7,
        stun: .04,
        //GENJUTSU
        genjutsu: 5,
        gen_power: 45,
        willpower: 2,
        chakra: 0,
        chakra_rec: 6,
        drain: 7,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 45,
        negative_energy: 47,
        cursed_tech: 'Thunderclap-Veil - Double Critical',
        curse_amount: .32,
        curse_duration: 6,
        curse_cost: 26,
        //DOMAIN
        dom_purity: 4,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Rhythm-Echo - Increase Willpower by 2',
        ninJutsu2cost: 16,
        ninJutsu2Dmg: 135,
        nin2amount: 2,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: 'Claws - Decrease Shield by 8%',
        nin_cost: 21,
        ninjutsu_pow: 185,
        ninamount: .08,
        ultEnhance: false,
        //BUFFS
        buff: 'Increase Genjutsu by 3',
        buff2: 'Decrease Attack by 25%',
        buff_acc: 70,
        buff2_acc: 65,
        image: 'https://64.media.tumblr.com/5a4d57c5a295356ef574e7ca4512b484/ace490199105949f-6f/s1280x1920/9dfa87a978d53b3bdf6446a37e0b7efcdeb74be5.jpg'
    },
    {
        name: 'Kishibe',
        nen_type: 'Enhancer',
        element: 'fighter',
        elm: fighter,
        hp: 3333,
        //PHYSICAL
        attack: 240,
        defense: 233,
        critical: .15,
        strength: 2,
        //MAGIC
        elm_attack: 155,
        elm_defense: 168,
        elm_efficiency: 1.2,
        potency: .10,
        //WEAPON
        weapon: 255,
        shield: 234,
        curse_crit: 0.12,
        weaponCurse: 'Accuracy',
        weapon_amount: 1,
        //SPEED / LUCK
        accuracy: 5,
        evasion: 7,
        luck: 2,
        stun: .05,
        //GENJUTSU
        genjutsu: 3,
        gen_power: 20,
        willpower: 5,
        chakra: 0,
        chakra_rec: 3,
        drain: 3,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 34,
        negative_energy: 35,
        cursed_tech: 'Projection-Sorcery - Double Evasion',
        curse_amount: 7,
        curse_duration: 6,
        curse_cost: 19,
        //DOMAIN
        dom_purity: 2,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Knife Devil Contract - Increase Weapon by 8%',
        ninJutsu2cost: 15,
        ninJutsu2Dmg: 185,
        nin2amount: .08,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Claw Devil contract - Increase Attack by 8%",
        nin_cost: 15,
        ninjutsu_pow: 185,
        ninamount: .08,
        ultEnhance: true,
        //BUFFS
        buff: 'Double Wither percent',
        buff2: 'Decrease Potency by 50%',
        buff_acc: 60,
        buff2_acc: 65,
        image: 'https://preview.redd.it/i-tried-to-make-kishibe-a-bit-more-lively-v0-ke8dx7n9oxoa1.jpg?width=640&crop=smart&auto=webp&s=30f8a2bebb02a1782f1418be2c76debf6493d0e9'
    },
    {
        name: 'Aki',
        nen_type: 'Specialist',
        element: 'Dark',
        elm: dark,
        hp: 3077,
        //PHYSICAL
        attack: 133,
        defense: 200,
        critical: .70,
        strength: 1.7,
        //MAGIC
        elm_attack: 135,
        elm_defense: 170,
        elm_efficiency: 1.2,
        potency: .10,
        //WEAPON
        weapon: 272,
        shield: 198,
        curse_crit: .27,
        weaponCurse: 'Shield',
        weapon_amount: 7,
        //SPEED / LUCK
        accuracy: 7,
        evasion: 7,
        luck: 7,
        stun: .07,
        //GENJUTSU
        genjutsu: 3,
        gen_power: 15,
        willpower: 2,
        chakra: 0,
        chakra_rec: 7,
        drain: 2,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 28,
        negative_energy: 34,
        cursed_tech: 'Divergent-Fist - Add 50 to attack',
        curse_amount: 50,
        curse_duration: 6,
        curse_cost: 17,
        //DOMAIN
        dom_purity: 9,
        dom_lethal: 40,
        dom_duration: 8,
        dom_cost: 27,
        //NINJUTSU
        ninjutsu2: 'Future-Devil Contract - Increase Evasion by 1',
        ninJutsu2cost: 17,
        ninJutsu2Dmg: 177,
        nin2amount: 1,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Curse-Devil Contract I - Halve Any stat",
        nin_cost: 70,
        ninjutsu_pow: 0,
        ninamount: 0,
        ultEnhance: false,
        //BUFFS
        buff: 'Curse Devil Contract II',
        buff2: 'Curse Devil Contract III - Erase 1 stat',
        buff_acc: 77,
        buff2_acc: 57,
        image: 'https://i.pinimg.com/736x/a8/26/45/a826458e9ec3b3e63687e831a0841546.jpg'
    },
    //// END /////
    /////// SUB-EMITTERS ////////
    {
        name: 'Akatsuki Sasuke',
        nen_type: 'Enhancer',
        element: 'Lightning',
        elm: lightning,
        hp: 2941,
        //PHYSICAL
        attack: 173,
        defense: 142,
        critical: .20,
        strength: 1.3,
        //MAGIC
        elm_attack: 214,
        elm_defense: 207,
        elm_efficiency: 1.7,
        potency: .25,
        //WEAPON
        weapon: 244,
        shield: 199,
        curse_crit: .18,
        weaponCurse: 'Magic-Def',
        weapon_amount: 12,
        //SPEED / LUCK
        accuracy: 7,
        evasion: 6,
        luck: 8,
        stun: .05,
        //GENJUTSU
        genjutsu: 9,
        gen_power: 60,
        willpower: 3,
        chakra: 0,
        chakra_rec: 4,
        drain: 15,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 33,
        negative_energy: 33,
        cursed_tech: 'Reverse - Increase Defense by 75',
        curse_amount: 75,
        curse_duration: 6,
        curse_cost: 12,
        //DOMAIN
        dom_purity: 2,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Chidori - Increase Magic by 5%',
        ninJutsu2cost: 12,
        ninJutsu2Dmg: 200,
        nin2amount: .05,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Sharingan - Increase Evasion by 1",
        nin_cost: 15,
        ninjutsu_pow: 135,
        ninamount: 1,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Potency by 30%',
        buff2: 'Decrease Will Power by 4',
        buff_acc: 70,
        buff2_acc: 60,
        image: 'https://i.pinimg.com/736x/e6/96/43/e6964375383d77adfa552aaffc174e84.jpg'
    },
    {
        name: 'Suigetsu',
        nen_type: 'Emitter',
        element: 'Water',
        elm: water,
        hp: 2898,
        //PHYSICAL
        attack: 132,
        defense: 157,
        critical: 0.32,
        strength: 1.3,
        //MAGIC
        elm_attack: 243,
        elm_defense: 189,
        elm_efficiency: 1.8,
        potency: 0.34,
        //WEAPON
        weapon: 226,
        shield: 163,
        curse_crit: .30,
        weaponCurse: 'Magic-Def',
        weapon_amount: 12,
        //SPEED / LUCK
        accuracy: 6,
        evasion: 5,
        luck: 7,
        stun: .06,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 10,
        willpower: 4,
        chakra: 0,
        chakra_rec: 5,
        drain: 3,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 30,
        negative_energy: 32,
        cursed_tech: 'Body-Manipulation - Double Evasion',
        curse_amount: 5,
        curse_duration: 6,
        curse_cost: 14,
        //DOMAIN
        dom_purity: 3,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Water-Formation-Wall - Increase Defense by 15%',
        ninJutsu2cost: 12,
        ninJutsu2Dmg: 135,
        nin2amount: .15,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: 'Water-Gun - Deal 325 Damage',
        nin_cost: 22,
        ninjutsu_pow: 325,
        ninamount: 0,
        ultEnhance: false,
        //BUFFS
        buff: 'Increase Shield by 20%',
        buff2: 'Decrease Attack by 20%',
        buff_acc: 65,
        buff2_acc: 70,
        image: 'https://static.wikia.nocookie.net/naruto/images/5/5e/Suigetsu_H%C5%8Dzuki_Parte_II_Anime.png/revision/latest?cb=20130308180649&path-prefix=es'
    },
    {
        name: 'Itachi',
        nen_type: 'Emitter',
        element: 'Fire',
        elm: fire,
        hp: 3105,
        //PHYSICAL
        attack: 181,
        defense: 168,
        critical: .40,
        strength: 1.5,
        //MAGIC
        elm_attack: 278,
        elm_defense: 254,
        elm_efficiency: 1.3,
        potency: .30,
        //WEAPON
        weapon: 152,
        shield: 163,
        curse_crit: .40,
        weaponCurse: 'Genjutsu',
        weapon_amount: 2,
        //SPEED / LUCK
        accuracy: 9,
        evasion: 7,
        luck: 2,
        stun: .05,
        //GENJUTSU
        genjutsu: 7,
        gen_power: 50,
        willpower: 5,
        chakra: 0,
        chakra_rec: 7,
        drain: 4,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 21,
        negative_energy: 20,
        cursed_tech: 'Black-Bird-Manipulation - Increase Gen-Power by 100',
        curse_amount: 100,
        curse_duration: 10,
        curse_cost: 25,
        //DOMAIN
        dom_purity: 2,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Amaterasu - Decrease Magic Defense by 8%',
        ninJutsu2cost: 15,
        ninJutsu2Dmg: 195,
        nin2amount: .08,
        ninEnhance: false,
        //ULTIMATE
        ninjutsu: "Yasaka-Magatama - Reduce Curse Recovery by 20",
        nin_cost: 30,
        ninjutsu_pow: 400,
        ninamount: 20,
        ultEnhance: false,
        //BUFFS
        buff: 'Increase Defense by 30%',
        buff2: 'Decrease Willpower by 3',
        buff_acc: 55,
        buff2_acc: 60,
        image: 'https://static.wikia.nocookie.net/denaruto3/images/3/3c/ItachiUchiha.PNG/revision/latest?cb=20120705195723&path-prefix=de'
    },
    {
        name: 'Amaterasu Sasuke',
        nen_type: 'Emitter',
        element: 'Fire',
        elm: fire,
        hp: 3264,
        //PHYSICAL
        attack: 158,
        defense: 240,
        critical: .15,
        strength: 1.3,
        //MAGIC
        elm_attack: 280,
        elm_defense: 185,
        elm_efficiency: 1.50,
        potency: .20,
        //WEAPON
        weapon: 166,
        shield: 225,
        curse_crit: .10,
        weaponCurse: 'Weapon',
        weapon_amount: 5,
        //SPEED / LUCK
        accuracy: 7,
        evasion: 2,
        luck: 2,
        stun: .04,
        //GENJUTSU
        genjutsu: 5,
        gen_power: 35,
        willpower: 7,
        chakra: 0,
        chakra_rec: 4,
        drain: 2,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 15,
        negative_energy: 15,
        cursed_tech: 'Disaster-Flames - Increase Potency to .50',
        curse_amount: .30,
        curse_duration: 6,
        curse_cost: 12,
        //DOMAIN
        dom_purity: 7,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Flame-Control Amaterasu - Increase Magic Defense by 10%',
        ninJutsu2cost: 15,
        ninJutsu2Dmg: 175,
        nin2amount: .10,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Amaterasu-Arrow - Decrease Magic defense by 25%",
        nin_cost: 28,
        ninjutsu_pow: 250,
        ninamount: .25,
        ultEnhance: false,
        //BUFFS
        buff: 'Increase Weapon by 20%',
        buff2: 'Decrease Evasion by 2',
        buff_acc: 65,
        buff2_acc: 65,
        image: 'https://w0.peakpx.com/wallpaper/513/74/HD-wallpaper-sasuke-black-and-white-sharingan-sasuke-black-uchiha-amaterasu-white-mangekyou-thumbnail.jpg'
    },
    {
        name: 'Feitan',
        nen_type: 'Transmuter',
        element: 'Fire',
        elm: fire,
        hp: 2988,
        //PHYSICAL
        attack: 132,
        defense: 138,
        critical: .75,
        strength: 1.6,
        //MAGIC
        elm_attack: 283,
        elm_defense: 234,
        elm_efficiency: 1.5,
        potency: .20,
        //WEAPON
        weapon: 219,
        shield: 186,
        curse_crit: .15,
        weaponCurse: 'Magic-Def',
        weapon_amount: 20,
        //SPEED / LUCK
        accuracy: 9,
        evasion: 9,
        luck: 4,
        stun: .04,
        //GENJUTSU
        genjutsu: 3,
        gen_power: 30,
        willpower: 2,
        chakra: 0,
        chakra_rec: 5,
        drain: 4,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 29,
        negative_energy: 35,
        cursed_tech: 'Disaster-Flames - Increase Potency to 80%',
        curse_amount: .60,
        curse_duration: 6,
        curse_cost: 15,
        //DOMAIN
        dom_purity: 7,
        dom_lethal: 90,
        dom_duration: 4,
        dom_cost: 25,
        //NINJUTSU
        ninjutsu2: 'Pain-Packer - Enhances Efficiency by 25%',
        ninJutsu2cost: 10,
        ninJutsu2Dmg: 155,
        nin2amount: .25,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Rising-Sun - Enhances Defense by 50%",
        nin_cost: 20,
        ninjutsu_pow: 245,
        ninamount: .50,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Shield by 25%',
        buff2: 'Decrease Magic by 25%',
        buff_acc: 70,
        buff2_acc: 65,
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/8/86/HxH2011_EP50_Feitan_Portrait.png/revision/latest?cb=20230121061055'
    },
    {
        name: 'Kakuzu',
        nen_type: 'Emitter',
        element: 'Sage',
        elm: sage,
        hp: 3410,
        //PHYSICAL
        attack: 215,
        defense: 235,
        critical: .23,
        strength: 2,
        //MAGIC
        elm_attack: 240,
        elm_defense: 166,
        elm_efficiency: 1,
        potency: .15,
        //WEAPON
        weapon: 128,
        shield: 195,
        curse_crit: .10,
        weaponCurse: 'GenJutsu',
        weapon_amount: 3,
        //SPEED / LUCK
        accuracy: 4,
        evasion: 3,
        luck: 2,
        stun: .03,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 30,
        willpower: 7,
        chakra: 0,
        chakra_rec: 7,
        drain: 3,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 15,
        negative_energy: 15,
        cursed_tech: 'Simple-Barrier - Increase Magic Defense by 80',
        curse_amount: 80,
        curse_duration: 6,
        curse_cost: 12,
        //DOMAIN
        dom_purity: 2,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Earth-Grudge-Fear Increase Shield by 10%',
        ninJutsu2cost: 15,
        ninJutsu2Dmg: 0,
        nin2amount: .10,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Heart-Mask - Recover 360 HP",
        nin_cost: 28,
        ninjutsu_pow: 0,
        ninamount: 360,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Accuracy by 3',
        buff2: 'Decrease Genjutsu by 2',
        buff_acc: 40,
        buff2_acc: 70,
        image: 'https://i.pinimg.com/236x/9d/40/38/9d4038be829e441d494f3f06a9c22f2c.jpg'
    },
    {
        name: 'Konan',
        nen_type: 'Manipulator',
        element: 'Grass',
        elm: grass,
        hp: 2867,
        //PHYSICAL
        attack: 125,
        defense: 174,
        critical: .10,
        strength: 1,
        //MAGIC
        elm_attack: 268,
        elm_defense: 239,
        elm_efficiency: 1.1,
        potency: .60,
        //WEAPON
        weapon: 114,
        shield: 139,
        curse_crit: .10,
        weaponCurse: 'Critical',
        weapon_amount: .10,
        //SPEED / LUCK
        accuracy: 4,
        evasion: 4,
        luck: 4,
        stun: .06,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 12,
        willpower: 7,
        chakra: 0,
        chakra_rec: 4,
        drain: 7,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 52,
        negative_energy: 28,
        cursed_tech: 'Falling-Blossom-Emotion - Halve chakra cost',
        curse_amount: 7,
        curse_duration: 6,
        curse_cost: 15,
        //DOMAIN
        dom_purity: 8,
        dom_lethal: 100,
        dom_duration: 5,
        dom_cost: 28,
        //NINJUTSU
        ninjutsu2: 'Explosive Tags - Increase Potency by 10%',
        ninJutsu2cost: 14,
        ninJutsu2Dmg: 165,
        nin2amount: .10,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Dance of the Shikigami - Increase Domain Duration by 1",
        nin_cost: 16,
        ninjutsu_pow: 0,
        ninamount: 1,
        ultEnhance: true,
        //BUFFS
        buff: 'Add 2 to Domain Purity',
        buff2: 'Decrease Weapon by 25%',
        buff_acc: 65,
        buff2_acc: 75,
        image: 'https://i.pinimg.com/originals/d8/08/eb/d808eb40caf400d332c02751eda72d68.jpg'
    },
    {
        name: 'Killua',
        nen_type: 'Transmuter',
        element: 'Lightning',
        elm: lightning,
        hp: 2942,
        //PHYSICAL
        attack: 212,
        defense: 134,
        critical: .40,
        strength: 1.25,
        //MAGIC
        elm_attack: 251,
        elm_defense: 199,
        elm_efficiency: 1.75,
        potency: .20,
        //WEAPON
        weapon: 110,
        shield: 235,
        curse_crit: .10,
        weaponCurse: 'Accuracy',
        weapon_amount: 1,
        //SPEED / LUCK
        accuracy: 5,
        evasion: 6,
        luck: 6,
        stun: .06,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 20,
        willpower: 2,
        chakra: 0,
        chakra_rec: 4,
        drain: 6,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 15,
        negative_energy: 12,
        cursed_tech: 'Electro-Strike-Manipulation - Increase Magic Attack by 75',
        curse_amount: 75,
        curse_duration: 6,
        curse_cost: 22,
        //DOMAIN
        dom_purity: 6,
        dom_lethal: 25,
        dom_duration: 4,
        dom_cost: 15,
        //NINJUTSU
        ninjutsu2: 'Whirlwind - Increase Evasion by 1',
        ninJutsu2cost: 11,
        ninJutsu2Dmg: 0,
        nin2amount: 1,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Eletric-Yo-Yo - Increase Stun",
        nin_cost: 12,
        ninjutsu_pow: 115,
        ninamount: .06,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Attack by 25%',
        buff2: 'Decrease Effiecieny by 80%',
        buff_acc: 70,
        buff2_acc: 70,
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/b/bd/HxH2011_EP147_Killua_Portrait.png/revision/latest?cb=20230904181904'
    },
    {
        name: 'Franklin',
        nen_type: 'Emitter',
        element: 'Earth',
        elm: earth,
        hp: 3318,
        //PHYSICAL
        attack: 128,
        defense: 265,
        critical: .05,
        strength: 1,
        //MAGIC
        elm_attack: 247,
        elm_defense: 252,
        elm_efficiency: 1.1,
        potency: .25,
        //WEAPON
        weapon: 214,
        shield: 164,
        curse_crit: .12,
        weaponCurse: 'Magic-Def',
        weapon_amount: 15,
        //SPEED / LUCK
        accuracy: 5,
        evasion: 2,
        luck: 5,
        stun: .05,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 10,
        willpower: 2,
        chakra: 0,
        chakra_rec: 3,
        drain: 10,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 22,
        negative_energy: 20,
        cursed_tech: 'Granite-Blast Deal 250 Damage',
        curse_amount: 250,
        curse_duration: 1,
        curse_cost: 20,
        //DOMAIN
        dom_purity: 3,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Nen-Bullets - Lower Magic Defense by 10%',
        ninJutsu2cost: 14,
        ninJutsu2Dmg: 175,
        nin2amount: .10,
        ninEnhance: false,
        //ULTIMATE
        ninjutsu: "Double-Machine-Gun - Increase Potency by 25%",
        nin_cost: 18,
        ninjutsu_pow: 235,
        ninamount: .25,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Weapon by 30%',
        buff2: 'Decrease Shield by 30%',
        buff_acc: 70,
        buff2_acc: 65,
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/6/62/HxH2011_EP58_Franklin_Portrait.png/revision/latest?cb=20230122063251'
    },
    {
        name: 'Yamato',
        nen_type: 'Emitter',
        element: 'Wood',
        elm: wood,
        hp: 3053,
        //PHYSICAL
        attack: 144,
        defense: 235,
        critical: .10,
        strength: 1.1,
        //MAGIC
        elm_attack: 246,
        elm_defense: 204,
        elm_efficiency: 1.8,
        potency: .18,
        //WEAPON
        weapon: 123,
        shield: 158,
        curse_crit: .14,
        weaponCurse: 'GenPower',
        weapon_amount: 10,
        //SPEED / LUCK
        accuracy: 5,
        evasion: 3,
        luck: 3,
        stun: .04,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 10,
        willpower: 2,
        chakra: 0,
        chakra_rec: 7,
        drain: 8,
        //CURSE
        cursed_energy: 16,
        cursed_recovery: 20,
        negative_energy: 22,
        cursed_tech: 'Domain-Amplification Double Duration',
        curse_amount: 5,
        curse_duration: 100,
        curse_cost: 22,
        //DOMAIN
        dom_purity: 5,
        dom_lethal: 85,
        dom_duration: 5,
        dom_cost: 21,
        //NINJUTSU
        ninjutsu2: 'Wood-Locking-Wall - Increase Shield by 15%',
        ninJutsu2cost: 15,
        ninJutsu2Dmg: 130,
        nin2amount: .15,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Great-Forest-Technique Reduce Chakra by 1",
        nin_cost: 21,
        ninjutsu_pow: 225,
        ninamount: 1,
        ultEnhance: false,
        //BUFFS
        buff: 'Double Stun',
        buff2: 'Decrease Purity by 2',
        buff_acc: 65,
        buff2_acc: 65,
        image: 'https://i.redd.it/zipny72okyv91.jpg'
    },
    {
        name: 'Pokkle',
        nen_type: 'Emitter',
        element: 'Fairy',
        elm: fairy,
        hp: 2893,
        //PHYSICAL
        attack: 118,
        defense: 156,
        critical: .10,
        strength: 1.3,
        //MAGIC
        elm_attack: 239,
        elm_defense: 238,
        elm_efficiency: 1.5,
        potency: .35,
        //WEAPON
        weapon: 226,
        shield: 172,
        curse_crit: .45,
        weaponCurse: 'Curse',
        weapon_amount: 8,
        //SPEED / LUCK
        accuracy: 8,
        evasion: 5,
        luck: 7,
        stun: .08,
        //GENJUTSU
        genjutsu: 6,
        gen_power: 60,
        willpower: 2,
        chakra: 0,
        chakra_rec: 6,
        drain: 2,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 25,
        negative_energy: 15,
        cursed_tech: 'Seven-Spectrum - Minus 6 Cost Ninjutsu',
        curse_amount: 6,
        curse_duration: 6,
        curse_cost: 15,
        //DOMAIN
        dom_purity: 1,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Purple-Arrow - Increase Magic by 5%',
        ninJutsu2cost: 13,
        ninJutsu2Dmg: 135,
        nin2amount: .05,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Orange-Arrow - Increase Evasion by 1",
        nin_cost: 18,
        ninjutsu_pow: 145,
        ninamount: 1,
        ultEnhance: true,
        //BUFFS
        buff: 'Stun rate plus .08',
        buff2: 'Decrease Accuracy by 2',
        buff_acc: 70,
        buff2_acc: 60,
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/0/0a/Pokkle_HxH_11.PNG/revision/latest?cb=20120323055002'
    },
    {
        name: 'Kalluto',
        nen_type: 'Emitter',
        element: 'Fairy',
        elm: fairy,
        hp: 2814,
        //PHYSICAL
        attack: 112,
        defense: 150,
        critical: .10,
        strength: 1,
        //MAGIC
        elm_attack: 244,
        elm_defense: 182,
        elm_efficiency: 2,
        potency: .28,
        //WEAPON
        weapon: 175,
        shield: 202,
        curse_crit: .40,
        weaponCurse: 'Magic',
        weapon_amount: 20,
        //SPEED / LUCK
        accuracy: 5,
        evasion: 6,
        luck: 7,
        stun: .06,
        //GENJUTSU
        genjutsu: 8,
        gen_power: 70,
        willpower: 5,
        chakra: 0,
        chakra_rec: 8,
        drain: 8,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 35,
        negative_energy: 65,
        cursed_tech: 'Falling-Blossom-Emotion - 8 off chakra cost',
        curse_amount: 8,
        curse_duration: 8,
        curse_cost: 16,
        //DOMAIN
        dom_purity: 2,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Explosive Tags - Increase Potency by 10%',
        ninJutsu2cost: 12,
        ninJutsu2Dmg: 145,
        nin2amount: .10,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Dance-of-the-Serpent's-Bite - Increase Power by 30%",
        nin_cost: 24,
        ninjutsu_pow: 300,
        ninamount: .30,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Weapon by 30%',
        buff2: 'Decrease Magic by 30%',
        buff_acc: 70,
        buff2_acc: 70,
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/b/bb/HxH2011_EP97_Kalluto_Close_Up.png/revision/latest?cb=20221123201432'
    },
    {
        name: 'Temari',
        nen_type: 'Emitter',
        element: 'Wind',
        elm: wind,
        hp: 2962,
        //PHYSICAL
        attack: 134,
        defense: 161,
        critical: .28,
        strength: 1.4,
        //MAGIC
        elm_attack: 246,
        elm_defense: 193,
        elm_efficiency: 1.75,
        potency: 0.30,
        //WEAPON
        weapon: 230,
        shield: 168,
        curse_crit: .40,
        weaponCurse: 'Magic',
        weapon_amount: 9,
        //SPEED / LUCK
        accuracy: 5,
        evasion: 3,
        luck: 6,
        stun: .06,
        //GENJUTSU
        genjutsu: 3,
        gen_power: 10,
        willpower: 4,
        chakra: 0,
        chakra_rec: 4,
        drain: 5,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 32,
        negative_energy: 28,
        cursed_tech: 'Simple-Domain - Increase Defense by 100',
        curse_amount: 100,
        curse_duration: 6,
        curse_cost: 16,
        //DOMAIN
        dom_purity: 4,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Kamaitachi - Increase Weapon Critical by 20%',
        ninJutsu2cost: 18,
        ninJutsu2Dmg: 165,
        nin2amount: .20,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: 'Kamikaze  - Traps Enemy in Wind-Vortex for 1 turn',
        nin_cost: 24,
        ninjutsu_pow: 230,
        ninamount: 0,
        ultEnhance: false,
        //BUFFS
        buff: 'Increase Magic Attack by 8%',
        buff2: 'Decrease Attack by 20%',
        buff_acc: 65,
        buff2_acc: 70,
        image: 'https://static.wikia.nocookie.net/naruto/images/b/b2/Temari_Part_II.png/revision/latest/scale-to-width-down/300?cb=20180131102417'
    },
    // END //
    ////// sub-Enhancer ///
    {
        name: 'Gon',
        nen_type: 'Enhancer',
        element: 'Fighter',
        elm: fighter,
        hp: 3085,
        //PHYSICAL
        attack: 253,
        defense: 238,
        critical: .30,
        strength: 1.5,
        //MAGIC
        elm_attack: 120,
        elm_defense: 166,
        elm_efficiency: 1.1,
        potency: .10,
        //WEAPON
        weapon: 196,
        shield: 192,
        curse_crit: .10,
        weaponCurse: 'Evasion',
        weapon_amount: 1,
        //SPEED / LUCK
        accuracy: 5,
        evasion: 6,
        luck: 8,
        stun: .08,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 15,
        willpower: 3,
        chakra: 0,
        chakra_rec: 7,
        drain: 0,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 35,
        negative_energy: 65,
        cursed_tech: 'Reverse-Flow-Recovery Increase Recovery by 8',
        curse_amount: 8,
        curse_duration: 6,
        curse_cost: 18,
        //DOMAIN
        dom_purity: 2,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Scissors - Increase Critical by 10%',
        ninJutsu2cost: 10,
        ninJutsu2Dmg: 175,
        nin2amount: .10,
        ninEnhance: false,
        //ULTIMATE
        ninjutsu: "Jajanken - Stengthen Jajanken by 200 | Reduce Recovery by 2",
        nin_cost: 20,
        ninjutsu_pow: 350,
        ninamount: 0,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Willpower by 4',
        buff2: 'Decrease Defense by 10%',
        buff_acc: 50,
        buff2_acc: 60,
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/3/3e/HxH2011_EP147_Gon_Portrait.png/revision/latest?cb=20230904181801'
    },
    {
        name: 'Phinks',
        nen_type: 'Enhancer',
        element: 'Fighter',
        elm: fighter,
        hp: 3415,
        //PHYSICAL
        attack: 264,
        defense: 255,
        critical: .28,
        strength: 1.6,
        //MAGIC
        elm_attack: 112,
        elm_defense: 150,
        elm_efficiency: 1.2,
        potency: 0.10,
        //WEAPON
        weapon: 185,
        shield: 215,
        curse_crit: .05,
        weaponCurse: 'Attack',
        weapon_amount: 10,
        //SPEED / LUCK
        accuracy: 4,
        evasion: 4,
        luck: 5,
        stun: .06,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 10,
        willpower: 7,
        chakra: 0,
        chakra_rec: 6,
        drain: 2,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 20,
        negative_energy: 12,
        cursed_tech: 'Reverse-Flow-Recovery Increace Recovery by 5',
        curse_amount: 5,
        curse_duration: 6,
        curse_cost: 16,
        //DOMAIN
        dom_purity: 7,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Ripper-Cyclotron',
        ninJutsu2cost: 12,
        ninJutsu2Dmg: 185,
        nin2amount: 0,
        ninEnhance: false,
        //ULTIMATE
        ninjutsu: "Ripper-Cyclotron 15x Increase Cyclotron by 50%",
        nin_cost: 30,
        ninjutsu_pow: 230,
        ninamount: .50,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Magic Defense by 10%',
        buff2: 'Decrease Weapon by 10%',
        buff_acc: 70,
        buff2_acc: 70,
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/8/88/HxH2011_EP41_Phinks_Portrait.png/revision/latest?cb=20221008055432'
    },
    {
        name: 'Uvogin',
        nen_type: 'Enhancer',
        element: 'Earth',
        elm: earth,
        hp: 3500,
        //PHYSICAL
        attack: 280,
        defense: 262,
        critical: .18,
        strength: 2,
        //MAGIC
        elm_attack: 130,
        elm_defense: 232,
        elm_efficiency: 1,
        potency: .06,
        //WEAPON
        weapon: 162,
        shield: 227,
        curse_crit: .05,
        weaponCurse: 'Weapon',
        weapon_amount: 20,
        //SPEED / LUCK
        accuracy: 4,
        evasion: 3,
        luck: 3,
        stun: .04,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 0,
        willpower: 2,
        chakra: 0,
        chakra_rec: 3,
        drain: 3,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 15,
        negative_energy: 10,
        cursed_tech: "Rage-Blast Increase Magic Defense by 100",
        curse_amount: 100,
        curse_duration: 6,
        curse_cost: 18,
        //DOMAIN
        dom_purity: 5,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'SCREAM - Decrease Evasion by 2',
        ninJutsu2cost: 14,
        ninJutsu2Dmg: 140,
        nin2amount: 2,
        ninEnhance: false,
        //ULTIMATE
        ninjutsu: "Big-Bang-Impact - Decrease Defense by 70%",
        nin_cost: 32,
        ninjutsu_pow: 750,
        ninamount: .70,
        ultEnhance: false,
        //BUFFS
        buff: 'Double Critical',
        buff2: 'Decrease GenPower by 20%',
        buff_acc: 50,
        buff2_acc: 50,
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/6/60/HxH2011_EP41_Uvogin_Portrait.png/revision/latest?cb=20230122192913'
    },
    {
        name: 'Yuji',
        nen_type: 'Enhancer',
        element: 'Ghost',
        elm: ghost,
        hp: 3396,
        //PHYSICAL
        attack: 257,
        defense: 246,
        critical: .23,
        strength: 1.65,
        //MAGIC
        elm_attack: 134,
        elm_defense: 197,
        elm_efficiency: 1.4,
        potency: .40,
        //WEAPON
        weapon: 171,
        shield: 155,
        curse_crit: .20,
        weaponCurse: 'Critical',
        weapon_amount: .10,
        //SPEED / LUCK
        accuracy: 5,
        evasion: 6,
        luck: 7,
        stun: .07,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 40,
        willpower: 4,
        chakra: 0,
        chakra_rec: 3,
        drain: 3,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 66,
        negative_energy: 35,
        cursed_tech: 'Black-Flash - 13/22',
        curse_amount: 0,
        curse_duration: 2,
        curse_cost: 13,
        //DOMAIN
        dom_purity: 6,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Heavenly-Restriction - Increase Defense by 8%',
        ninJutsu2cost: 12,
        ninJutsu2Dmg: 150,
        nin2amount: .08,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Claws - Increase Shield by 10%",
        nin_cost: 15,
        ninjutsu_pow: 155,
        ninamount: .10,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Curse Recvoery by 15',
        buff2: 'Decrease Curse Recovery by 15',
        buff_acc: 65,
        buff2_acc: 65,
        image: 'https://i.pinimg.com/736x/89/70/0d/89700d9de4deb5f1099c7770d879625b.jpg'
    },
    {
        name: 'Deidara',
        nen_type: 'Conjuror',
        element: 'Earth',
        elm: earth,
        hp: 2992,
        //PHYSICAL
        attack: 231,
        defense: 188,
        critical: .60,
        strength: 1.2,
        //MAGIC
        elm_attack: 218,
        elm_defense: 196,
        elm_efficiency: 1.5,
        potency: .20,
        //WEAPON
        weapon: 110,
        shield: 225,
        curse_crit: .08,
        weaponCurse: 'Gen-Power',
        weapon_amount: 15,
        //SPEED / LUCK
        accuracy: 5,
        evasion: 4,
        luck: 2,
        stun: .07,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 10,
        willpower: 5,
        chakra: 0,
        chakra_rec: 7,
        drain: 4,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 15,
        negative_energy: 14,
        cursed_tech: 'Granite-Blast - Deal 300 Damage',
        curse_amount: 260,
        curse_duration: 1,
        curse_cost: 18,
        //DOMAIN
        dom_purity: 6,
        dom_lethal: 50,
        dom_duration: 6,
        dom_cost: 30,
        //NINJUTSU
        ninjutsu2: 'C3 - Increase Attack by 5%',
        ninJutsu2cost: 15,
        ninJutsu2Dmg: 145,
        nin2amount: .05,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "C4 Karura - Increase Lethal by 20",
        nin_cost: 20,
        ninjutsu_pow: 0,
        ninamount: 20,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Evasion by 3',
        buff2: 'Decrease Purity by 3',
        buff_acc: 60,
        buff2_acc: 60,
        image: 'https://static.wikia.nocookie.net/naruto/images/3/33/Deidara_Eye_Scope.png/revision/latest?cb=20160109162348'
    },
    {
        name: 'Neji',
        nen_type: 'Enhancer',
        element: 'Fairy',
        elm: fairy,
        hp: 2875,
        //PHYSICAL
        attack: 231,
        defense: 174,
        critical: .65,
        strength: 1.2,
        //MAGIC
        elm_attack: 165,
        elm_defense: 220,
        elm_efficiency: 1.4,
        potency: .15,
        //WEAPON
        weapon: 148,
        shield: 190,
        curse_crit: .06,
        weaponCurse: 'Purity',
        weapon_amount: 1,
        //SPEED / LUCK
        accuracy: 9,
        evasion: 3,
        luck: 2,
        stun: .06,
        //GENJUTSU
        genjutsu: 1,
        gen_power: 10,
        willpower: 5,
        chakra: 0,
        chakra_rec: 5,
        drain: 2,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 50,
        negative_energy: 12,
        cursed_tech: 'Domain- Amplification Increase Domain Duration by 4',
        curse_amount: 4,
        curse_duration: 100,
        curse_cost: 18,
        //DOMAIN
        dom_purity: 6,
        dom_lethal: 85,
        dom_duration: 8,
        dom_cost: 26,
        //NINJUTSU
        ninjutsu2: '8-Trigram-64-Palms - Increase Stun by 8%',
        ninJutsu2cost: 12,
        ninJutsu2Dmg: 100,
        nin2amount: .08,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Rotation - Increase Sheild by 15%",
        nin_cost: 16,
        ninjutsu_pow: 200,
        ninamount: .15,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Accuracy by 5',
        buff2: 'Decrease Stun by 100%',
        buff_acc: 50,
        buff2_acc: 65,
        image: 'https://static.wikia.nocookie.net/eroninja/images/7/79/Neji.png/revision/latest?cb=20180124002919'
    },
    {
        name: 'Rock Lee',
        nen_type: 'Engancer',
        element: 'Earth',
        elm: earth,
        hp: 2872,
        //PHYSICAL
        attack: 238,
        defense: 194,
        critical: .24,
        strength: 1.7,
        //MAGIC
        elm_attack: 106,
        elm_defense: 152,
        elm_efficiency: 1,
        potency: .08,
        //WEAPON
        weapon: 211,
        shield: 232,
        curse_crit: .08,
        weaponCurse: 'Recovery',
        weapon_amount: 1,
        //SPEED / LUCK
        accuracy: 5,
        evasion: 8,
        luck: 7,
        stun: .05,
        //GENJUTSU
        genjutsu: 1,
        gen_power: 0,
        willpower: 2,
        chakra: 0,
        chakra_rec: 4,
        drain: 4,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 45,
        negative_energy: 22,
        cursed_tech: '8th-Gate - Increase Attack by 100',
        curse_amount: 100,
        curse_duration: 100,
        curse_cost: 45,
        //DOMAIN
        dom_purity: 2,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Leaf-Hurricane - Increase stun by 6%',
        ninJutsu2cost: 14,
        ninJutsu2Dmg: 200,
        nin2amount: .06,
        ninEnhance: false,
        //ULTIMATE
        ninjutsu: "Gate-Release - Increase Evasion by 1",
        nin_cost: 20,
        ninjutsu_pow: 0,
        ninamount: 1,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Curse Recovery by 15',
        buff2: 'Decrease Defense by 10%',
        buff_acc: 50,
        buff2_acc: 70,
        image: 'https://imgix.ranker.com/user_node_img/50088/1001756931/original/the-lotus-of-the-leaf-village-photo-u1?auto=format&q=60&fit=crop&fm=pjpg&dpr=2&w=355'
    },
    {
        name: 'Bisky',
        nen_type: 'Enhancer',
        element: 'Fairy',
        elm: fairy,
        hp: 3491,
        //PHYSICAL
        attack: 280,
        defense: 271,
        critical: .16,
        strength: 2,
        //MAGIC
        elm_attack: 164,
        elm_defense: 185,
        elm_efficiency: 2,
        potency: .20,
        //WEAPON
        weapon: 148,
        shield: 219,
        curse_crit: .05,
        weaponCurse: 'Attack',
        weapon_amount: 50,
        //SPEED / LUCK
        accuracy: 5,
        evasion: 3,
        luck: 3,
        stun: .04,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 30,
        willpower: 6,
        chakra: 0,
        chakra_rec: 5,
        drain: 2,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 24,
        negative_energy: 12,
        cursed_tech: 'Granite-Blast',
        curse_amount: 300,
        curse_duration: 1,
        curse_cost: 24,
        //DOMAIN
        dom_purity: 7,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Flex - Increase Magic Defense by 8%',
        ninJutsu2cost: 14,
        ninJutsu2Dmg: 0,
        nin2amount: .08,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Magical-Esthetician - Recover 355 HP",
        nin_cost: 30,
        ninjutsu_pow: 0,
        ninamount: 355,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Accuracy by 4',
        buff2: 'Decrease Weapon by 10%',
        buff_acc: 40,
        buff2_acc: 65,
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/c/cd/Biscuit_Krueger_CA_Portrait.png/revision/latest?cb=20190630140152'
    },
    {
        name: 'Adult Gon',
        nen_type: 'Enhancer',
        element: 'Ghost',
        elm: ghost,
        hp: 3500,
        //PHYSICAL
        attack: 300,
        defense: 248,
        critical: .20,
        strength: 1.8,
        //MAGIC
        elm_attack: 131,
        elm_defense: 201,
        elm_efficiency: 1.3,
        potency: .10,
        //WEAPON
        weapon: 128,
        shield: 172,
        curse_crit: .08,
        weaponCurse: 'Evasion',
        weapon_amount: 1,
        //SPEED / LUCK
        accuracy: 5,
        evasion: 8,
        luck: 4,
        stun: .05,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 40,
        willpower: 5,
        chakra: 0,
        chakra_rec: 8,
        drain: 2,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 20,
        negative_energy: 18,
        cursed_tech: 'Projection-Sorcery - Double Evasion',
        curse_amount: 8,
        curse_duration: 6,
        curse_cost: 18,
        //DOMAIN
        dom_purity: 7,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Scissors - Increase Critical by .05',
        ninJutsu2cost: 16,
        ninJutsu2Dmg: 150,
        nin2amount: .05,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Jajanken - Increase Jajanken by 200 | Reduce Recovery by 2",
        nin_cost: 25,
        ninjutsu_pow: 400,
        ninamount: 0,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Curse Recovery by 15',
        buff2: 'Decrease Curse Recovery by 15',
        buff_acc: 50,
        buff2_acc: 50,
        image: 'https://pbs.twimg.com/profile_images/1397430377996824577/QXzPZoyh_400x400.jpg'
    },
    {
        name: 'Female Titan',
        nen_type: 'Transmuter',
        element: 'Water',
        elm: water,
        hp: 2986,
        //PHYSICAL
        attack: 253,
        defense: 236,
        critical: .28,
        strength: 1.25,
        //MAGIC
        elm_attack: 124,
        elm_defense: 183,
        elm_efficiency: 1.3,
        potency: .50,
        //WEAPON
        weapon: 210,
        shield: 200,
        curse_crit: .10,
        weaponCurse: 'Genjutsu',
        weapon_amount: 1,
        //SPEED / LUCK
        accuracy: 6,
        evasion: 7,
        luck: 3,
        stun: .06,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 10,
        willpower: 7,
        chakra: 0,
        chakra_rec: 6,
        drain: 6,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 15,
        negative_energy: 15,
        cursed_tech: 'Idle-Death-Gamble - Can Devil Contract 1000',
        curse_amount: 0,
        curse_duration: 100,
        curse_cost: 22,
        //DOMAIN
        dom_purity: 3,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Ice-Fist - Increase Attack by 8%',
        ninJutsu2cost: 15,
        ninJutsu2Dmg: 170,
        nin2amount: .08,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Ice-Harden - Increase Shield 15%",
        nin_cost: 17,
        ninjutsu_pow: 150,
        ninamount: .15,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Weapon by 30%',
        buff2: 'Decrease Luck by 2',
        buff_acc: 50,
        buff2_acc: 50,
        image: 'https://static.wikia.nocookie.net/shingekinokyojin/images/4/44/Female_Titan_%28Anime%29_character_image_%28Annie_Leonhart%29.png/revision/latest?cb=20170708025046'
    },
    {
        name: 'Sage Naruto',
        nen_type: 'Enhancer',
        element: 'Wind',
        elm: wind,
        hp: 3453,
        //PHYSICAL
        attack: 245,
        defense: 232,
        critical: .30,
        strength: 1.45,
        //MAGIC
        elm_attack: 132,
        elm_defense: 145,
        elm_efficiency: 2,
        potency: .50,
        //WEAPON
        weapon: 160,
        shield: 199,
        curse_crit: .15,
        weaponCurse: 'Curse',
        weapon_amount: 15,
        //SPEED / LUCK
        accuracy: 7,
        evasion: 5,
        luck: 4,
        stun: .04,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 45,
        willpower: 3,
        chakra: 0,
        chakra_rec: 6,
        drain: 0,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 10,
        negative_energy: 10,
        cursed_tech: 'Cursed-Kyuubi - Increase Recovery by 8',
        curse_amount: 8,
        curse_duration: 10,
        curse_cost: 24,
        //DOMAIN
        dom_purity: 8,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Rasengan - Decrease Curse Recovery by 8',
        ninJutsu2cost: 12,
        ninJutsu2Dmg: 200,
        nin2amount: .08,
        ninEnhance: false,
        //ULTIMATE
        ninjutsu: "Rasenshuriken - Decrease Defense by 30%",
        nin_cost: 24,
        ninjutsu_pow: 400,
        ninamount: .30,
        ultEnhance: false,
        //BUFFS
        buff: 'Increase Genjutsu by 5',
        buff2: 'Decrease Genjutsu by 3',
        buff_acc: 40,
        buff2_acc: 50,
        image: 'https://i.pinimg.com/736x/d4/bf/7f/d4bf7f663ef81e3eef8b945ae16e3b84.jpg'
    },
    {
        name: 'Attack Titan',
        nen_type: 'Enhancer',
        element: 'Fighter',
        elm: fighter,
        hp: 3466,
        //PHYSICAL
        attack: 273,
        defense: 240,
        critical: .20,
        strength: 1.65,
        //MAGIC
        elm_attack: 120,
        elm_defense: 208,
        elm_efficiency: 1.3,
        potency: .40,
        //WEAPON
        weapon: 131,
        shield: 139,
        curse_crit: .05,
        weaponCurse: 'Purity',
        weapon_amount: 1,
        //SPEED / LUCK
        accuracy: 5,
        evasion: 4,
        luck: 5,
        stun: .05,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 10,
        willpower: 3,
        chakra: 0,
        chakra_rec: 6,
        drain: 4,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 45,
        negative_energy: 18,
        cursed_tech: 'Rumbling - Increase Attack by 85',
        curse_amount: 85,
        curse_duration: 100,
        curse_cost: 33,
        //DOMAIN
        dom_purity: 8,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Fury - Increase Crit',
        ninJutsu2cost: 20,
        ninJutsu2Dmg: 0,
        nin2amount: .40,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Roar - Increase Strength by 1",
        nin_cost: 24,
        ninjutsu_pow: 0,
        ninamount: 1,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Accuracy by 2',
        buff2: 'Decrease Attack by 20%',
        buff_acc: 65,
        buff2_acc: 50,
        image: 'https://static.wikia.nocookie.net/shingekinokyojin/images/a/ae/Attack_Titan_%28Anime%29_character_image_%28Eren_Jaeger%29.png/revision/latest/scale-to-width-down/1000?cb=20170513212951'
    },
    {
        name: 'Todo',
        nen_type: 'Enhancer',
        element: 'Earth',
        elm: earth,
        hp: 3494,
        //PHYSICAL
        attack: 264,
        defense: 230,
        critical: .30,
        strength: 1.75,
        //MAGIC
        elm_attack: 113,
        elm_defense: 136,
        elm_efficiency: 1,
        potency: .01,
        //WEAPON
        weapon: 184,
        shield: 218,
        curse_crit: .09,
        weaponCurse: 'Defense',
        weapon_amount: 12,
        //SPEED / LUCK
        accuracy: 5,
        evasion: 7,
        luck: 2,
        stun: .03,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 10,
        willpower: 4,
        chakra: 0,
        chakra_rec: 3,
        drain: 6,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 55,
        negative_energy: 15,
        cursed_tech: 'Black-Flash - 15/15',
        curse_amount: 0,
        curse_duration: 1,
        curse_cost: 15,
        //DOMAIN
        dom_purity: 7,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Playful-Cloud - Increase Attack by 6%',
        ninJutsu2cost: 15,
        ninJutsu2Dmg: 100,
        nin2amount: .06,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "Vibra-Slap - Increase Curse by 10",
        nin_cost: 20,
        ninjutsu_pow: 170,
        ninamount: 10,
        ultEnhance: true,
        //BUFFS
        buff: 'Increase Accuracy by 2',
        buff2: 'Decrease Magic by 10%',
        buff_acc: 50,
        buff2_acc: 45,
        image: 'https://static.wikia.nocookie.net/jujutsu-kaisen/images/e/ef/Aoi_Todo.jpg/revision/latest?cb=20210904074234&path-prefix=pl'
    },
    {
        name: 'Netero',
        nen_type: 'Enhancer',
        element: 'Fighter',
        elm: fighter,
        hp: 3275,
        //PHYSICAL
        attack: 297,
        defense: 215,
        critical: .25,
        strength: 1.5,
        //MAGIC
        elm_attack: 130,
        elm_defense: 205,
        elm_efficiency: 1,
        potency: 0.15,
        //WEAPON
        weapon: 145,
        shield: 225,
        curse_crit: .20,
        weaponCurse: 'Defense',
        weapon_amount: 25,
        //SPEED / LUCK
        accuracy: 15,
        evasion: 5,
        luck: 2,
        stun: .06,
        //GENJUTSU
        genjutsu: 2,
        gen_power: 10,
        willpower: 3,
        chakra: 0,
        chakra_rec: 10,
        drain: 2,
        //CURSE
        cursed_energy: 0,
        cursed_recovery: 25,
        negative_energy: 15,
        cursed_tech: 'Ninety-Ninth-Hand - Add 100 to Attack',
        curse_amount: 100,
        curse_duration: 6,
        curse_cost: 25,
        //DOMAIN
        dom_purity: 7,
        dom_lethal: 0,
        dom_duration: 0,
        dom_cost: 0,
        //NINJUTSU
        ninjutsu2: 'Third-Hand - Increase Evasion by 1',
        ninJutsu2cost: 15,
        ninJutsu2Dmg: 185,
        nin2amount: 1,
        ninEnhance: true,
        //ULTIMATE
        ninjutsu: "First-Hand - Deal 330 Damage",
        nin_cost: 16,
        ninjutsu_pow: 330,
        ninamount: 0,
        ultEnhance: false,
        //BUFFS
        buff: 'Increase Recovery by 2',
        buff2: 'Zero-Hand - Deal 1000 Damage',
        buff_acc: 30,
        buff2_acc: 0,
        image: 'https://64.media.tumblr.com/b3add61800c26d58b7e6a7627c9b2c00/e1d0c57be4c47966-59/s1280x1920/960f28661bd237e20ba6b5a71a74a9d127f51e9f.jpg'
    },
    ///////////////////// END ////////////////////////
]
