let fight = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w3jw-de938798-b424-41a6-97a3-2da7cf54d589.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2FiYTFhNzU2LWQ5NTUtNDNmNi1hMmU5LTViN2Q2MDQwNjg1NFwvZDUwdzNqdy1kZTkzODc5OC1iNDI0LTQxYTYtOTdhMy0yZGE3Y2Y1NGQ1ODkucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.HGh80g4xxzz2u9_PBJAONxCOaoxy1OW9J2yi0oKhHuA'
let lightning = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w476-824f2616-a647-4a21-a284-8a35db3dd34b.png/v1/fit/w_720,h_720/electric_energy_by_humac1_d50w476-375w-2x.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NzIwIiwicGF0aCI6IlwvZlwvYWJhMWE3NTYtZDk1NS00M2Y2LWEyZTktNWI3ZDYwNDA2ODU0XC9kNTB3NDc2LTgyNGYyNjE2LWE2NDctNGEyMS1hMjg0LThhMzVkYjNkZDM0Yi5wbmciLCJ3aWR0aCI6Ijw9NzIwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.TWz0rw0cPCDqnXtwripN9OXA1V9qf5jNwrZYea4YZ7w'
let water = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w3fi-85063943-452c-4b80-8db1-5cf8ff52df52.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2FiYTFhNzU2LWQ5NTUtNDNmNi1hMmU5LTViN2Q2MDQwNjg1NFwvZDUwdzNmaS04NTA2Mzk0My00NTJjLTRiODAtOGRiMS01Y2Y4ZmY1MmRmNTIucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.voroYLPZMwgOCJjmkVuK6GepgSaDWAjj25Ptq5CuGJg'
let pyschic = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w3p6-aa8c3894-d7bf-450b-99be-f608d14e1e4a.png/v1/fit/w_720,h_720/psychic_energy_by_humac1_d50w3p6-375w-2x.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NzIwIiwicGF0aCI6IlwvZlwvYWJhMWE3NTYtZDk1NS00M2Y2LWEyZTktNWI3ZDYwNDA2ODU0XC9kNTB3M3A2LWFhOGMzODk0LWQ3YmYtNDUwYi05OWJlLWY2MDhkMTRlMWU0YS5wbmciLCJ3aWR0aCI6Ijw9NzIwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.X66lXufkAxkVXIW4UYQjAbHyGeoKZ9pBYVr-q8__wHo'
let dark = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w4az-9be9ea46-fdf8-4e18-957e-9c7fcded42e5.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2FiYTFhNzU2LWQ5NTUtNDNmNi1hMmU5LTViN2Q2MDQwNjg1NFwvZDUwdzRhei05YmU5ZWE0Ni1mZGY4LTRlMTgtOTU3ZS05YzdmY2RlZDQyZTUucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.BrPQc3irmKVsAQ5EGkKyiVD1uJWriOOxsupE6eGEzbo'
let wind = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/b0b4c759-ad9c-4425-a9f4-ab89e2fd9837/dfqnx68-7fe93ac3-842b-4884-8e62-b8f60a4611f1.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2IwYjRjNzU5LWFkOWMtNDQyNS1hOWY0LWFiODllMmZkOTgzN1wvZGZxbng2OC03ZmU5M2FjMy04NDJiLTQ4ODQtOGU2Mi1iOGY2MGE0NjExZjEucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.YhuFxSx0nTcNbc7JJB74NP8mzfASk6vSJHIEXLWEfAg'
let earth = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/472f4a44-0b68-46a9-bfd1-ffca5f5d411f/dhcbrn5-e71b4cf7-1a9a-4179-95dc-52386fe03cd5.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzQ3MmY0YTQ0LTBiNjgtNDZhOS1iZmQxLWZmY2E1ZjVkNDExZlwvZGhjYnJuNS1lNzFiNGNmNy0xYTlhLTQxNzktOTVkYy01MjM4NmZlMDNjZDUucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.xoGUxe8T8CLCmOdKrMnEyNpg3bwi8YmFZNQ9nh5WVRs'
let grass = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w40k-75281ddb-5dc8-4eb8-9321-d5c901815eed.png/v1/fit/w_720,h_720/leaf_energy_by_humac1_d50w40k-375w-2x.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NzIwIiwicGF0aCI6IlwvZlwvYWJhMWE3NTYtZDk1NS00M2Y2LWEyZTktNWI3ZDYwNDA2ODU0XC9kNTB3NDBrLTc1MjgxZGRiLTVkYzgtNGViOC05MzIxLWQ1YzkwMTgxNWVlZC5wbmciLCJ3aWR0aCI6Ijw9NzIwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.hkzFeGcwL8-ZytHLvV07CmX3RHjcImRYgtZkUHGuNzM'
let fire = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w437-315a34c4-85c2-4d07-ae4d-6b42a25233bf.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2FiYTFhNzU2LWQ5NTUtNDNmNi1hMmU5LTViN2Q2MDQwNjg1NFwvZDUwdzQzNy0zMTVhMzRjNC04NWMyLTRkMDctYWU0ZC02YjQyYTI1MjMzYmYucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.kytndezX-kNW72WN893L_sOKoTnQYmvnqvJ79VVV8w8'
let sage = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aba1a756-d955-43f6-a2e9-5b7d60406854/d50w4gu-bcf44127-7bc3-468d-b148-1af8cf4e7ac0.png/v1/fit/w_720,h_720/colorless_energy_by_humac1_d50w4gu-375w-2x.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NzIwIiwicGF0aCI6IlwvZlwvYWJhMWE3NTYtZDk1NS00M2Y2LWEyZTktNWI3ZDYwNDA2ODU0XC9kNTB3NGd1LWJjZjQ0MTI3LTdiYzMtNDY4ZC1iMTQ4LTFhZjhjZjRlN2FjMC5wbmciLCJ3aWR0aCI6Ijw9NzIwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.I2hRnHXhqZrAh05uX4UyxVC8C-iVQrj00LWU7nvS9C8'
const database = [
    {
        name: 'Chrollo',
        nen_type: 'Specialist',
        element: 'Sage',
        hp: 2680,
        attack: 168,
        defense: 195,
        elm_attack: 226,
        elm_defense: 225,
        elm_efficiency: 1,
        critical: .30,
        strength: 2,
        potency: .35,
        accuracy: 4,
        evasion: 4,
        chakra: 0,
        chakra_rec: 7,
        // ninjutsu and luck
        chakra_attack: 'Sun and Moon',
        cost: 26,
        chakra_pow: 400,
        ninjutsu: "Bandit's Secret - Halve Any Stat",
        nin_cost: 55,
        ninjutsu_pow: 200,
        buff: 'Switch One stat with Opponents stat',
        buff2: 'Use opponents Buff',
        buff_acc: 25,
        buff2_acc: 50,
        ninjutsu2: 'Order Stamp - Enhance Genjutsu by 60%',
        ninJutsu2cost: 21,
        ninJutsu2Dmg: 200,
        luck: 6,
        // genjutsu
        genjutsu: 4,
        gen_power: 75,
        willpower: 8,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 50, // 100 is best
        cursed_tech: 'Projection-Sorcery - Increase Evasion by 5',
        curse_amount: 5,
        curse_duration: 6,
        curse_cost: 9,
        dom_purity: 6,
        dom_lethal: 75,
        dom_duration: 3,
        dom_cost: 30,
        dom_name: '',
        //additonal
        elm: sage,
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/7/78/Chrollo_Lucilfer_GI_Portrait.png/revision/latest?cb=20130502190618'
    },
    {
        name: 'Hisoka',
        nen_type: 'Transmutter',
        element: 'Fire',
        attack: 218,
        defense: 186,
        elm_attack: 193,
        elm_defense: 178,
        elm_efficiency: 1.3,
        critical: .50,
        hp: 2744,
        strength: 1.5,
        potency: .35,
        accuracy: 6,
        evasion: 5,
        buff: 'Increase Attack by 30%',
        buff2: 'Halve chakra cost',
        buff_acc: 70,
        buff2_acc: 50,
        chakra: 0, // max 100
        chakra_rec: 7,
        cost: 12,
        chakra_attack: 'Bungee Gum',
        chakra_pow: 250,
        ninjutsu: "Texture Surprise - Enhances Bungee Gum by 50%",
        nin_cost: 26,
        ninjutsu_pow: 255,
        ninjutsu2: 'Bungee Gum',
        ninJutsu2cost: 12,
        ninJutsu2Dmg: 255,
        luck: 6,
        genjutsu: 3,
        gen_power: 65,
        willpower: 5,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 50, // 100 is best
        cursed_tech: 'Falling-Blossom-Emotion - Ninjutsu cost halved',
        curse_amount: 6, //instead of prompt
        curse_duration: 6,
        curse_cost: 6,
        dom_purity: 4,
        dom_lethal: 120,
        dom_duration: 3,
        dom_cost: 28,
        dom_name: '',
        elm: fire,
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/2/29/Hisoka_Morow_YC_Portrait.png/revision/latest?cb=20190123172039'
    },
    {
        name: 'Feitan',
        nen_type: 'Transmutter',
        element: 'Fire',
        attack: 147,
        defense: 135,
        elm_attack: 246,
        elm_defense: 201,
        elm_efficiency: 1.8,
        critical: .80,
        hp: 2368,
        strength: 1.7,
        potency: .25,
        accuracy: 9,
        evasion: 8,
        buff: 'Increase Defense by 40%',
        buff2: 'Decrease Elemental Defense by 30%',
        buff_acc: 60,
        buff2_acc: 65,
        chakra: 0, // max 100
        chakra_rec: 6,
        cost: 8,
        chakra_attack: 'Short Sword',
        chakra_pow: 165,
        ninjutsu: "Rising Sun - Enhances defense by 100%",
        nin_cost: 44,
        ninjutsu_pow: 666,
        ninjutsu2: 'Pain Packer - Enhances Elemental by 8%',
        ninJutsu2cost: 15,
        ninJutsu2Dmg: 185,
        elm: fire,
        luck: 7,
        genjutsu: 5,
        gen_power: 70,
        willpower: 3,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 60, // 100 is best
        cursed_tech: 'Disaster-Flames - Increase Potency by .50',
        curse_amount: .50, //instead of prompt
        curse_duration: 6,
        curse_cost: 6,
        dom_purity: 6,
        dom_lethal: 85,
        dom_duration: 5,
        dom_cost: 28,
        dom_name: '',
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/8/86/HxH2011_EP50_Feitan_Portrait.png/revision/latest?cb=20230121061055'
    },
    {
        name: 'Illumi',
        nen_type: 'Manipulator',
        element: 'Dark',
        attack: 108,
        defense: 203,
        elm_attack: 199,
        elm_defense: 233,
        elm_efficiency: 1.6,
        critical: .25,
        hp: 2411,
        strength: 1.8,
        potency: .30,
        accuracy: 9,
        evasion: 7,
        buff: 'Decrease Opponents Accuracy by 25%',
        buff2: 'Decrease Opponents Will Power by 80%',
        buff_acc: 75,
        buff2_acc: 70,
        chakra: 0, // max 100
        chakra_rec: 11,
        cost: 15,
        chakra_attack: 'Needle People',
        chakra_pow: 190,
        ninjutsu2: "Body Alteration - Boost after casting Confusion",
        ninJutsu2cost: 10,
        ninJutsu2Dmg: 100,
        ninjutsu: 'Hypnotic Spell - Increase Gen Power by 50%',
        nin_cost: 28,
        ninjutsu_pow: 190,
        elm: dark,
        luck: 7,
        genjutsu: 9,
        gen_power: 70,
        willpower: 4,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 60, // 100 is best
        cursed_tech: 'Brain-Manipulation - Decrease a stat by 20%',
        curse_amount: 0, //instead of prompt
        curse_duration: 1,
        curse_cost: 10,
        dom_purity: 6,
        dom_lethal: 65,
        dom_duration: 5,
        dom_cost: 30,
        dom_name: '',
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/7/72/Illumi_Zoldyck_HCE_Portrait.png/revision/latest/scale-to-width/360?cb=20181227022223'
    },
    {
        name: 'Phinks',
        nen_type: 'Enhancer',
        element: 'Fighter',
        attack: 256,
        defense: 185,
        elm_attack: 113,
        elm_defense: 138,
        elm_efficiency: 1.8,
        critical: .25,
        hp: 2952,
        strength: 2,
        potency: .2,
        accuracy: 5,
        evasion: 4,
        buff: 'Increase Elemental Defense by 50%',
        buff2: 'Decrease Opponents Defense by 25%',
        buff_acc: 50,
        buff2_acc: 70,
        chakra: 0, // max 100
        chakra_rec: 5,
        ninjutsu: 'Ripper Cyclotron 15x - Double Cyclotron Power',
        cost: 8,
        chakra_attack: 'Ripper Cyclotron',
        chakra_pow: 255,
        ninjutsu2: "Ripper Cyclotron",
        ninJutsu2cost: 8,
        ninJutsu2Dmg: 255,
        nin_cost: 42,
        ninjutsu_pow: 415,
        elm: fight,
        luck: 4,
        genjutsu: 2,
        gen_power: 20,
        willpower: 2,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 30, // 100 is best
        cursed_tech: 'Divergent-Fist - Increase Attack by 44',
        curse_amount: 44, //instead of prompt
        curse_duration: 6,
        curse_cost: 14,
        dom_purity: 2,
        dom_lethal: 10,
        dom_duration: 2,
        dom_cost: 30,
        dom_name: '',
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/8/88/HxH2011_EP41_Phinks_Portrait.png/revision/latest?cb=20221008055432'
    },
    {
        name: 'Machi',
        nen_type: 'Transmutter',
        element: 'Lightning',
        attack: 175,
        defense: 110,
        elm_attack: 215,
        elm_defense: 135,
        elm_efficiency: 1.8,
        critical: .7,
        hp: 2133,
        strength: 1.8,
        potency: .6,
        accuracy: 5,
        evasion: 9,
        buff: 'Increase Defense by 50%',
        buff2: 'Decrease Accuracy by 10%',
        buff_acc: 50,
        buff2_acc: 70,
        chakra: 0, // max 100
        chakra_rec: 6,
        cost: 8,
        chakra_attack: 'Ninjitsu Attack',
        chakra_pow: 175,
        ninjutsu: "Nen Threads - Take two turns after capture",
        nin_cost: 25,
        ninjutsu_pow: 135,
        ninjutsu2: 'Nen Stiches - Recover 200 Hp',
        ninJutsu2cost: 20,
        ninJutsu2Dmg: 0,
        elm: lightning,
        luck: 6,
        genjutsu: 2,
        gen_power: 20,
        willpower: 6,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 40, // 100 is best
        cursed_tech: 'Reverse - Increase Defense by 100',
        curse_amount: 100, //instead of prompt
        curse_duration: 8,
        curse_cost: 11,
        dom_purity: 2,
        dom_lethal: 10,
        dom_duration: 2,
        dom_cost: 30,
        dom_name: '',
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/4/4c/Machi_Komacine_HA_Portrait.png/revision/latest?cb=20131116122706'
    },
    {
        name: 'Shizuku',
        nen_type: 'Conjuror',
        element: 'Wind',
        attack: 113,
        defense: 190,
        elm_attack: 169,
        elm_defense: 190,
        elm_efficiency: 2,
        critical: .25,
        hp: 2512,
        strength: 2,
        potency: .1,
        accuracy: 5,
        evasion: 7,
        buff: 'Increase Defense by 35%',
        buff2: 'Increase Elemental Defense by 35%',
        buff_acc: 65,
        buff2_acc: 65,
        chakra: 0, // max 100
        chakra_rec: 8,
        cost: 15,
        chakra_attack: 'Blinky',
        chakra_pow: 325,
        ninjutsu: "Enhanced Blinky - Increase  Chakra Recovery by 2",
        nin_cost: 15,
        ninjutsu_pow: 355,
        ninjutsu2: 'Inhale - Reduce Chakra Recovery by 2',
        ninJutsu2cost: 15,
        ninJutsu2Dmg: 210,
        elm: wind,
        luck: 4,
        genjutsu: 4,
        gen_power: 30,
        willpower: 2,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 55, // 100 is best
        cursed_tech: 'Falling-Blossom-Emotion take 6 off Chakra cost',
        curse_amount: 6, //instead of prompt
        curse_duration: 6,
        curse_cost: 6,
        dom_purity: 2,
        dom_lethal: 10,
        dom_duration: 2,
        dom_cost: 30,
        dom_name: '',
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/9/9e/HxH2011_EP53_Shizuku_Portrait.png/revision/latest?cb=20230122061315'
    },
    {
        name: 'Shalnark',
        nen_type: 'Manipulator',
        element: 'Grass',
        attack: 178,
        defense: 181,
        elm_attack: 105,
        elm_defense: 147,
        elm_efficiency: 1.6,
        critical: .20,
        hp: 2341,
        strength: 1.8,
        potency: .85,
        accuracy: 5,
        evasion: 5,
        buff2: 'Increase Critical by 300%',
        buff: 'Increase Elemental Defense by 40%',
        buff_acc: 70,
        buff2_acc: 35,
        chakra: 0, // max 100
        chakra_rec: 8,
        cost: 8,
        chakra_attack: 'Black Voice',
        chakra_pow: 150,
        ninjutsu: "Auto Pilot Mode - Enhance Strength by 100%",
        nin_cost: 50,
        ninjutsu_pow: 500,
        ninjutsu2: 'Black Voice Control - Reduce any Stat by 10%',
        ninJutsu2cost: 14,
        ninJutsu2Dmg: 150,
        elm: grass,
        luck: 7,
        genjutsu: 7,
        gen_power: 40,
        willpower: 8,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 50, // 100 is best
        cursed_tech: 'Brain-Manipulation - Decrease any stat by 10%',
        curse_amount: 0, //instead of prompt
        curse_duration: 1,
        curse_cost: 8,
        dom_purity: 6,
        dom_lethal: 70,
        dom_duration: 5,
        dom_cost: 27,
        dom_name: '',
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/c/c3/HxH2011_EP53_Shalnark_Portrait.png/revision/latest?cb=20221008053250'
    },
    {
        name: 'Nobunaga',
        nen_type: 'Enhancer',
        element: 'Dark',
        attack: 237,
        defense: 170,
        elm_attack: 158,
        elm_defense: 133,
        elm_efficiency: 1.6,
        critical: .70,
        hp: 2791,
        strength: 1.65,
        potency: .30,
        accuracy: 9,
        evasion: 3,
        buff: 'Increase Strength by 25%',
        buff2: 'Increase Elemental Defense by 50%',
        buff_acc: 50,
        buff2_acc: 50,
        chakra: 0, // max 100
        chakra_rec: 5,
        cost: 9,
        chakra_attack: 'En strike',
        chakra_pow: 260,
        ninjutsu: "Dark Bushido - Reduce Genjutsu by 80%",
        nin_cost: 30,
        ninjutsu_pow: 400,
        ninjutsu2: 'Iaidō Master - Increase Element Defense by 8%',
        ninJutsu2cost: 18,
        ninJutsu2Dmg: 270,
        elm: dark,
        luck: 5,
        genjutsu: 4,
        gen_power: 30,
        willpower: 4,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 65, // 100 is best
        cursed_tech: 'Blade of the Right Hand - Increase Attack by 55',
        curse_amount: 55, //instead of prompt
        curse_duration: 6,
        curse_cost: 8,
        dom_purity: 6,
        dom_lethal: 60,
        dom_duration: 4,
        dom_cost: 20,
        dom_name: '',
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/4/46/HxH2011_EP50_Nobunaga_Portrait.png/revision/latest?cb=20230122183803'
    },
    {
        name: 'Uvogin',
        nen_type: 'Enhancer',
        element: 'Earth',
        nen_type: 'Enhancer',
        element: 'Earth',
        attack: 265,
        defense: 230,
        elm_attack: 30,
        elm_defense: 194,
        elm_efficiency: 1.1,
        critical: .35,
        hp: 3000,
        strength: 2,
        potency: 1,
        accuracy: 3,
        evasion: 4,
        buff: 'Increase Accuracy by 100%',
        buff2: 'Increase Critical by 100%',
        buff_acc: 75,
        buff2_acc: 40,
        chakra: 0, // max 100
        chakra_rec: 3,
        cost: 13,
        chakra_attack: 'KILLSHOT',
        chakra_pow: 365,
        ninjutsu: "SCREAM - Decrease Accuracy by 70%",
        nin_cost: 22,
        ninjutsu_pow: 400,
        ninjutsu2: 'Big Bang Impact - Decrease Defense by 50%',
        ninJutsu2cost: 26,
        ninJutsu2Dmg: 375,
        elm: earth,
        luck: 4,
        genjutsu: 3,
        gen_power: 30,
        willpower: 4,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 30, // 100 is best
        cursed_tech: 'Muscular-Expansion - Doubles Strength',
        curse_amount: 2, //instead of prompt
        curse_duration: 6,
        curse_cost: 12,
        dom_purity: 6,
        dom_lethal: 10,
        dom_duration: 2,
        dom_cost: 30,
        dom_name: '',
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/6/60/HxH2011_EP41_Uvogin_Portrait.png/revision/latest?cb=20230122192913'
    },
    {
        name: 'Pakunoda',
        nen_type: 'Specialist',
        element: 'Psychic',
        attack: 112,
        defense: 148,
        elm_attack: 134,
        elm_defense: 162,
        elm_efficiency: 1,
        critical: 1.5,
        hp: 2323,
        strength: 1.2,
        potency: .80,
        accuracy: 10,
        evasion: 4,
        buff: 'Increase Elemental Defense by 75%',
        buff2: 'Increase Defense by 75%',
        buff_acc: 70,
        buff2_acc: 70,
        chakra: 0, // max 100
        chakra_rec: 13,
        cost: 15,
        chakra_attack: 'Psychometry',
        chakra_pow: 200,
        ninjutsu: "Memory Bomb - Decrease Stats by 25%",
        nin_cost: 40,
        ninjutsu_pow: 275,
        ninjutsu2: 'Nen Bullets - Decrease Stat by 40%',
        ninJutsu2cost: 45,
        ninJutsu2Dmg: 200,
        elm: pyschic,
        luck: 9,
        genjutsu: 7,
        gen_power: 70,
        willpower: 7,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 60, // 100 is best
        cursed_tech: 'Idle Death Gamble - Can gamble 800 health',
        curse_amount: 0, //instead of prompt
        curse_duration: 6,
        curse_cost: 11,
        dom_purity: 7,
        dom_lethal: 125,
        dom_duration: 2,
        dom_cost: 30,
        dom_name: '',
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/d/da/Pakunoda_YC_Portrait.png/revision/latest?cb=20190124184929'
    },
    {
        name: 'Franklin',
        nen_type: 'Emitter',
        element: 'Water',
        attack: 77,
        defense: 180,
        elm_attack: 228,
        elm_defense: 135,
        elm_efficiency: 1.2,
        critical: .25,
        hp: 2977,
        strength: 1.2,
        potency: .20,
        accuracy: 4,
        evasion: 4,
        buff: 'Increase Recovery by 100%',
        buff2: 'Increase Potency by 50%',
        buff_acc: 40,
        buff2_acc: 40,
        chakra: 0, // max 100
        chakra_rec: 4,
        cost: 5,
        chakra_attack: '',
        chakra_pow: 200,
        ninjutsu: "Double Machine Gun - Increase Nen Bullets by 50%",
        nin_cost: 30,
        ninjutsu_pow: 400,
        ninjutsu2: 'Nen Bullets',
        ninJutsu2cost: 8,
        ninJutsu2Dmg: 200,
        elm: water,
        luck: 7,
        genjutsu: 4,
        gen_power: 25,
        willpower: 4,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 35, // 100 is best
        cursed_tech: 'Hairpin - Increase Potency by .55',
        curse_amount: .55, //instead of prompt
        curse_duration: 6,
        curse_cost: 8,
        dom_purity: 2,
        dom_lethal: 25,
        dom_duration: 2,
        dom_cost: 30,
        dom_name: '',
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/6/62/HxH2011_EP58_Franklin_Portrait.png/revision/latest?cb=20230122063251'
    },
    {
        name: 'Bonolenov',
        nen_type: 'Conjuror',
        element: 'Wind',
        attack: 111,
        defense: 160,
        elm_attack: 205,
        elm_defense: 160,
        elm_efficiency: 2,
        critical: .40,
        hp: 2616,
        strength: 1.3,
        potency: .50,
        accuracy: 5,
        evasion: 4,
        buff: 'Increase Chakra Recovery by 30%',
        buff2: 'Decrease Opponents Chakra Recovery by 30%',
        buff_acc: 70,
        buff2_acc: 50,
        chakra: 0, // max 100
        chakra_rec: 7,
        cost: 15,
        chakra_attack: 'Battle Cantabile: Prologue',
        chakra_pow: 280,
        ninjutsu2: "Battle Cantabile: Jupiter - Increase Gen Power by 40%",
        ninJutsu2cost: 28,
        ninJutsu2Dmg: 300,
        nin_cost: 35,
        ninjutsu_pow: 350,
        ninjutsu: 'Battle Cantabile: Metamorphosen - Decrease Accuracy by 40',
        elm: wind,
        luck: 3,
        genjutsu: 8,
        gen_power: 80,
        willpower: 6,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 65, // 100 is best
        cursed_tech: 'Simple-Barrier',
        curse_amount: 80, //instead of prompt
        curse_duration: 6,
        curse_cost: 12,
        dom_purity: 7,
        dom_lethal: 50,
        dom_duration: 10,
        dom_cost: 34,
        dom_name: '',
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/f/fc/HxH2011_EP96_Bonolenov_Portrait.png/revision/latest?cb=20230123153232'
    },

    {
        name: 'Armor Titan',
        nen_type: 'Transmuter',
        element: 'Earth',
        attack: 265,
        defense: 305,
        elm_attack: 50,
        elm_defense: 265,
        elm_efficiency: 1,
        critical: .15,
        hp: 3000,
        strength: 1.2,
        potency: .2,
        accuracy: 4,
        evasion: 1,
        buff: 'Double Acuracy/ halve Defense',
        buff2: 'Increase WillPower by 2',
        buff_acc: 90,
        buff2_acc: 55,
        chakra: 0,
        chakra_rec: 3,
        cost: 10,
        chakra_attack: 'Ram',
        chakra_pow: 300,
        ninjutsu2: "Smash - Decrease Defense by 10%",
        ninJutsu2cost: 12,
        ninJutsu2Dmg: 345,
        nin_cost: 25,
        ninjutsu_pow: 700,
        ninjutsu: 'RAGE - Decrease Defense by 100%',
        elm: earth,
        luck: 3,
        genjutsu: 1,
        gen_power: 15,
        willpower: 3,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 40, // 100 is best
        cursed_tech: 'Muscular-Expansion - Critical x 4',
        curse_amount: .45, //instead of prompt
        curse_duration: 6,
        curse_cost: 10,
        dom_purity: 8,
        dom_lethal: 10,
        dom_duration: 2,
        dom_cost: 30,
        dom_name: '',
        image: 'https://i.redd.it/k2fme3l6e8m61.jpg'
    },

    {
        name: 'Obito',
        nen_type: 'Specialist',
        element: 'Dark',
        attack: 170,
        defense: 210,
        elm_attack: 225,
        elm_defense: 210,
        elm_efficiency: 1.4,
        critical: .15,
        hp: 2753,
        strength: 1.2,
        potency: .1,
        accuracy: 5,
        evasion: 11,
        buff: 'Increase Potency by 500%',
        buff2: 'Increase Chakra Recovery by 2',
        buff_acc: 45,
        buff2_acc: 45,
        chakra: 0,
        chakra_rec: 6,
        cost: 12,
        chakra_attack: 'Uchiha Flame',
        chakra_pow: 280,
        ninjutsu2: "Kamui - Trapped in Dimensional Space 1 turn",
        ninJutsu2cost: 26,
        ninJutsu2Dmg: 245,
        nin_cost: 48,
        ninjutsu_pow: 280,
        ninjutsu: 'Demonic Chakra Chains - Increase Kamui by 1 turn',
        elm: dark,
        luck: 2,
        genjutsu: 6,
        gen_power: 25,
        willpower: 3,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 60, // 100 is best
        cursed_tech: 'Hollow-Wicker-Basket - Invincible to all Stat attacks',
        curse_amount: 0, //instead of prompt
        curse_duration: 6,
        curse_cost: 15,
        dom_purity: 5,
        dom_lethal: 60,
        dom_duration: 6,
        dom_cost: 25,
        dom_name: '',
        image: 'https://static.wikia.nocookie.net/denaruto3/images/b/bb/ObitoUchiha.png/revision/latest?cb=20140816152828&path-prefix=de'
    },
    {
        name: 'Itachi',
        nen_type: 'Emitter',
        element: 'Fire',
        attack: 198,
        defense: 215,
        elm_attack: 229,
        elm_defense: 128,
        elm_efficiency: 1.7,
        critical: .65,
        hp: 2277,
        strength: 1.4,
        potency: .20,
        accuracy: 11,
        evasion: 3,
        buff: 'Triple Genjutsu Power',
        buff2: 'Increase Element Defense by 30%',
        buff_acc: 35,
        buff2_acc: 70,
        chakra: 0,
        chakra_rec: 6,
        cost: 10,
        chakra_attack: 'Fire Ball',
        chakra_pow: 220,
        ninjutsu2: "Amaterasu - Decrease Element Def or Def by 20%",
        ninJutsu2cost: 24,
        ninJutsu2Dmg: 320,
        nin_cost: 32,
        ninjutsu_pow: 600,
        ninjutsu: 'Yasaka Magatama - Increase Chakra by 3%',
        elm: fire,
        luck: 2,
        genjutsu: 5,
        gen_power: 33,
        willpower: 9,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 60, // 100 is best
        cursed_tech: 'Black-Bird-Manipulation - Triple Genjutsu',
        curse_amount: 10, //instead of prompt
        curse_duration: 6,
        curse_cost: 14,
        dom_purity: 5,
        dom_lethal: 60,
        dom_duration: 6,
        dom_cost: 28,
        dom_name: '',
        image: 'https://static.wikia.nocookie.net/denaruto3/images/3/3c/ItachiUchiha.PNG/revision/latest?cb=20120705195723&path-prefix=de'
    },
    {
        name: 'Akatsuki Sasuke',
        nen_type: 'Enhancer',
        element: 'Lightning',
        attack: 258,
        defense: 126,
        elm_attack: 188,
        elm_defense: 215,
        elm_efficiency: 1.5,
        critical: .35,
        hp: 2266,
        strength: 1.7,
        potency: .25,
        accuracy: 6,
        evasion: 6,
        buff: 'Double Critical',
        buff2: 'Double Elmental Attack',
        buff_acc: 40,
        buff2_acc: 35,
        chakra: 0,
        chakra_rec: 6,
        cost: 10,
        chakra_attack: 'Chidori',
        chakra_pow: 230,
        ninjutsu2: "Sharingan - Increase Evasion by 2",
        ninJutsu2cost: 18,
        ninJutsu2Dmg: 320,
        nin_cost: 34,
        ninjutsu_pow: 400,
        ninjutsu: 'Amaterasu - Decrease Elemental defense by 20%',
        elm: lightning,
        luck: 4,
        genjutsu: 5,
        gen_power: 60,
        willpower: 5,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 40, // 100 is best
        cursed_tech: 'Reverse - Increase Defense by 75',
        curse_amount: 75, //instead of prompt
        curse_duration: 6,
        curse_cost: 8,
        dom_purity: 4,
        dom_lethal: 20,
        dom_duration: 4,
        dom_cost: 30,
        dom_name: '',
        image: 'https://i.pinimg.com/736x/e6/96/43/e6964375383d77adfa552aaffc174e84.jpg'
    },
    {
        name: 'Hidan',
        nen_type: 'Manipulator',
        element: 'Dark',
        attack: 235,
        defense: 180,
        elm_attack: 92,
        elm_defense: 189,
        elm_efficiency: 1.2,
        critical: .55,
        hp: 2563,
        strength: 1.75,
        potency: .15,
        accuracy: 4,
        evasion: 4,
        buff: 'Blood Draw * 1/2 allows nen',
        buff2: 'Pentagram full use of nen',
        buff_acc: 50,
        buff2_acc: 50,
        chakra: 0,
        chakra_rec: 5,
        cost: 15,
        chakra_attack: 'Triple Blade Scyth',
        chakra_pow: 300,
        ninjutsu2: "Jahshin’s Curse - Wither a stat by 30% *not twice",
        ninJutsu2cost: 20,
        ninJutsu2Dmg: 300,
        nin_cost: 30,
        ninjutsu_pow: 0,
        ninjutsu: 'Immortality - Recover 300 HP',
        elm: dark,
        luck: 8,
        genjutsu: 2,
        gen_power: 30,
        willpower: 2,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 50, // 100 is best
        cursed_tech: 'Idle-Death-Gamble - Can Devil Contract 700',
        curse_amount: 0, //instead of prompt
        curse_duration: 6,
        curse_cost: 16,
        dom_purity: 2,
        dom_lethal: 20,
        dom_duration: 4,
        dom_cost: 30,
        dom_name: '',
        image: 'https://i.pinimg.com/474x/94/4a/97/944a97524606a98af81120fa453b07e6.jpg'
    },
    {
        name: 'Deidara',
        nen_type: 'Conjuror',
        element: 'Earth',
        attack: 205,
        defense: 153,
        elm_attack: 128,
        elm_defense: 167,
        elm_efficiency: 1.7,
        critical: .75,
        hp: 2249,
        strength: 1.4,
        potency: .50,
        accuracy: 5,
        evasion: 4,
        buff: 'Decrease Evasion by 50%',
        buff2: 'Fly Increase Evasion by 100%',
        buff_acc: 60,
        buff2_acc: 30,
        chakra: 0,
        chakra_rec: 6,
        cost: 4,
        chakra_attack: 'C2',
        chakra_pow: 125,
        ninjutsu2: "C3 - Increase attack by 15%",
        ninJutsu2cost: 18,
        ninJutsu2Dmg: 225,
        nin_cost: 33,
        ninjutsu_pow: 285,
        ninjutsu: 'C4 Karura - Cast Kotoamatsukami',
        elm: earth,
        luck: 7,
        genjutsu: 2,
        gen_power: 15,
        willpower: 5,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 40, // 100 is best
        cursed_tech: 'Granite-Blast - 500 Damage',
        curse_amount: 500, //instead of prompt
        curse_duration: 1,
        curse_cost: 20,
        dom_purity: 2,
        dom_lethal: 20,
        dom_duration: 4,
        dom_cost: 30,
        dom_name: '',
        image: 'https://static.wikia.nocookie.net/naruto/images/3/33/Deidara_Eye_Scope.png/revision/latest?cb=20160109162348'
    },
    {
        name: 'Pain',
        nen_type: 'Specialist',
        element: 'Psychic',
        attack: 175,
        defense: 147,
        elm_attack: 266,
        elm_defense: 159,
        elm_efficiency: 2,
        critical: .20,
        hp: 2505,
        strength: 1.2,
        potency: .20,
        accuracy: 7,
        evasion: 3,
        buff: 'Change Element Affinity',
        buff2: 'Recover 300 HP',
        buff_acc: 40,
        buff2_acc: 55,
        chakra: 0,
        chakra_rec: 5,
        cost: 18,
        chakra_attack: 'Gaikido',
        chakra_pow: 270,
        ninjutsu2: "Shinra Tensei - Increase either Defense by 20%",
        ninJutsu2cost: 28,
        ninJutsu2Dmg: 305,
        nin_cost: 60,
        ninjutsu_pow: 1000,
        ninjutsu: 'Chibaku Tensei - Own Chakra havled/ both def reduced by half',
        elm: pyschic,
        luck: 3,
        genjutsu: 6,
        gen_power: 45,
        willpower: 2,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 50, // 100 is best
        cursed_tech: 'Limitless-Reversal: Red',
        curse_amount: 50, //instead of prompt
        curse_duration: 1,
        curse_cost: 25,
        dom_purity: 8,
        dom_lethal: 10,
        dom_duration: 4,
        dom_cost: 30,
        dom_name: '',
        image: 'https://i.redd.it/y8xbcb5tiooa1.jpg'
    },
    {
        name: 'Sasori',
        nen_type: 'Manipulator',
        element: 'Water',
        attack: 129,
        defense: 229,
        elm_attack: 129,
        elm_defense: 229,
        elm_efficiency: 1.6,
        critical: .20,
        hp: 2505,
        strength: 1,
        potency: 1.2,
        accuracy: 5,
        evasion: 4,
        buff: 'Increase Attack by 25%',
        buff2: 'Decrease Elemental Attack by 25%',
        buff_acc: 70,
        buff2_acc: 70,
        chakra: 0,
        chakra_rec: 6,
        cost: 12,
        chakra_attack: 'Water Laser',
        chakra_pow: 12,
        ninjutsu2: "Poison - Any 2 of Darkness, Confuson, Silence",
        ninJutsu2cost: 22,
        ninJutsu2Dmg: 0,
        nin_cost: 40,
        ninjutsu_pow: 500,
        ninjutsu: '10,000 Puppets - Increase Attack by 100%',
        elm: water,
        luck: 4,
        genjutsu: 10,
        gen_power: 60,
        willpower: 4,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 40, // 100 is best
        cursed_tech: 'Albatross - Increase Element Attack by 100',
        curse_amount: 100, //instead of prompt
        curse_duration: 6,
        curse_cost: 15,
        dom_purity: 3,
        dom_lethal: 30,
        dom_duration: 5,
        dom_cost: 30,
        dom_name: '',
        image: 'https://i.pinimg.com/236x/3a/8f/da/3a8fdaabc0abd426c7c09e8b0588949a.jpg'
    },
    {
        name: 'Konan',
        nen_type: 'Manipulator',
        element: 'Wind',
        attack: 230,
        defense: 143,
        elm_attack: 205,
        elm_defense: 134,
        elm_efficiency: 1.6,
        critical: .20,
        hp: 2186,
        strength: 1.4,
        potency: .60,
        accuracy: 5,
        evasion: 5,
        buff: 'Decrease Genjutsu by .20',
        buff2: 'Increase Elemental Defense 25%',
        buff_acc: 70,
        buff2_acc: 75,
        chakra: 0,
        chakra_rec: 7,
        cost: 12,
        chakra_attack: 'Paper Shuriken',
        chakra_pow: 180,
        ninjutsu2: "Explosive Tags - Increase critical by 50%",
        ninJutsu2cost: 21,
        ninJutsu2Dmg: 280,
        nin_cost: 36,
        ninjutsu_pow: 375,
        ninjutsu: 'Dance of the Shikigami - Increase Stength by 50%',
        elm: wind,
        luck: 7,
        genjutsu: 4,
        gen_power: 40,
        willpower: 4,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 55, // 100 is best
        cursed_tech: 'Resonance - Incrase Critical by .65',
        curse_amount: .65, //instead of prompt
        curse_duration: 6,
        curse_cost: 9,
        dom_purity: 5,
        dom_lethal: 50,
        dom_duration: 5,
        dom_cost: 31,
        dom_name: '',
        image: 'https://i.pinimg.com/originals/d8/08/eb/d808eb40caf400d332c02751eda72d68.jpg'
    },
    {
        name: 'Aki',
        nen_type: 'Manipulator',
        element: 'Dark',
        attack: 215,
        defense: 175,
        elm_attack: 150,
        elm_defense: 150,
        elm_efficiency: 1.6,
        critical: .70,
        hp: 2277,
        strength: 1.4,
        potency: .30,
        accuracy: 7,
        evasion: 6,
        buff: 'Curse Devil Contract Ⅱ Halve self/enemy Def',
        buff2: 'Curse Devil Contract Ⅲ Halve self/enemy Def',
        buff_acc: 50,
        buff2_acc: 25,
        chakra: 0,
        chakra_rec: 7,
        cost: 13,
        chakra_attack: '',
        chakra_pow: 250,
        ninjutsu2: "Future Devil Contract - Increase Attack by 15%",
        ninJutsu2cost: 21,
        ninJutsu2Dmg: 315,
        nin_cost: 13,
        ninjutsu_pow: 250,
        ninjutsu: 'Fox Devil Contract',
        elm: dark,
        luck: 7,
        genjutsu: 3,
        gen_power: 20,
        willpower: 4,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 60, // 100 is best
        cursed_tech: 'Blade of the right hand - Increase Attack by 60',
        curse_amount: 60, //instead of prompt
        curse_duration: 6,
        curse_cost: 12,
        dom_purity: 2,
        dom_lethal: 20,
        dom_duration: 2,
        dom_cost: 30,
        dom_name: '',
        image: 'https://i.pinimg.com/736x/a8/26/45/a826458e9ec3b3e63687e831a0841546.jpg'
    },
    {
        name: 'Orochimaru',
        nen_type: 'Conjuror',
        element: 'Grass',
        attack: 126,
        defense: 216,
        elm_attack: 186,
        elm_defense: 216,
        elm_efficiency: 1.9,
        critical: .20,
        hp: 2345,
        strength: 1.2,
        potency: .40,
        accuracy: 5,
        evasion: 7,
        buff: 'Dcrease Attack by 30%',
        buff2: 'Decrease Elemental Attack by 30%',
        buff_acc: 70,
        buff2_acc: 70,
        chakra: 0,
        chakra_rec: 8,
        cost: 15,
        chakra_attack: 'Rashōmon gates',
        chakra_pow: 265,
        ninjutsu2: "Great White Snake - Decrease Accuracy by 2",
        ninJutsu2cost: 25,
        ninJutsu2Dmg: 250,
        nin_cost: 42,
        ninjutsu_pow: 300,
        ninjutsu: 'Living Corpse Reincarnation - Use One Character Trait',
        elm: grass,
        luck: 6,
        genjutsu: 6,
        gen_power: 60,
        willpower: 4,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 65, // 100 is best
        cursed_tech: 'Idle-Transfiguration - Decrease Any Stat by 20%',
        curse_amount: 0, //instead of prompt
        curse_duration: 1,
        curse_cost: 20,
        dom_purity: 2,
        dom_lethal: 20,
        dom_duration: 2,
        dom_cost: 30,
        dom_name: '',
        image: 'https://static.wikia.nocookie.net/narutolightningchronicles/images/e/e8/Orochimaru2.jpg/revision/latest?cb=20120916043631'
    },
    {
        name: 'Kishibe',
        nen_type: 'Enhancer',
        element: 'Fighter',
        attack: 271,
        defense: 179,
        elm_attack: 141,
        elm_defense: 138,
        elm_efficiency: 1.1,
        critical: .40,
        hp: 2745,
        strength: 1.5,
        potency: .10,
        accuracy: 8,
        evasion: 6,
        buff: 'Increase Elemental Defense by 30%',
        buff2: 'Increase Chakra Recovery by 3',
        buff_acc: 65,
        buff2_acc: 65,
        chakra: 0,
        chakra_rec: 5,
        cost: 11,
        chakra_attack: '',
        chakra_pow: 111,
        ninjutsu2: "Claw Devil Contract",
        ninJutsu2cost: 11,
        ninJutsu2Dmg: 111,
        nin_cost: 22,
        ninjutsu_pow: 333,
        ninjutsu: 'Knife Devil Contract - Doubles Claw damage',
        elm: fight,
        luck: 3,
        genjutsu: 3,
        gen_power: 30,
        willpower: 3,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 55, // 100 is best
        cursed_tech: 'Projection-Sorcery - Double Evasion',
        curse_amount: 6, //instead of prompt
        curse_duration: 6,
        curse_cost: 10,
        dom_purity: 7,
        dom_lethal: 10,
        dom_duration: 2,
        dom_cost: 30,
        dom_name: '',
        image: 'https://preview.redd.it/i-tried-to-make-kishibe-a-bit-more-lively-v0-ke8dx7n9oxoa1.jpg?width=640&crop=smart&auto=webp&s=30f8a2bebb02a1782f1418be2c76debf6493d0e9'
    },
    {
        name: 'Shaiapouf',
        nen_type: 'Manipulation',
        element: 'Wind',
        hp: 2371,
        attack: 131,
        defense: 129,
        elm_attack: 218,
        elm_defense: 255,
        elm_efficiency: 1.6,
        critical: .15,
        strength: 1,
        potency: .60,
        accuracy: 4,
        evasion: 5,
        chakra: 0,
        chakra_rec: 6,
        // ninjutsu and luck and buff
        ninjutsu: "Beelzebub - Increase Evasion by 20%",
        nin_cost: 12,
        ninjutsu_pow: 155,
        ninjutsu2: 'Spiritual Message - Double Genjutsu Power',
        ninJutsu2cost: 31,
        ninJutsu2Dmg: 310,
        buff: 'Reduce Will Power by 85%',
        buff2: 'Increase Domain purity by 25%',
        buff_acc: 65,
        buff2_acc: 50,
        luck: 5,
        // genjutsu
        genjutsu: 8,
        gen_power: 30,
        willpower: 4,
        // cursed attacks
        cursed_energy: 0,
        cursed_recovery: 70, // 100 is best
        cursed_tech: "Idle-Transfiguration - Decrease any stat by 20%",
        curse_duration: 1,
        curse_cost: 12,
        dom_purity: 10,
        dom_lethal: 235,
        dom_duration: 7,
        dom_cost: 20,
        dom_name: 'Cocoon',
        //additonal
        elm: water,
        image: 'https://static.wikia.nocookie.net/hunterxhunter/images/a/a2/109_-_Shaiapouf_portrait.png/revision/latest?cb=20150902224149'
    },
];
